### ISSUE TITLE
Question - how to add a cordova plugin in Developer App

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1010]
I want to try a plugin in Developer App through My ScratchPad. May you help me how to add non-listed plugins ? (Say cordova-local-notifications)

**Comment by cookieguru** [comment]
You'll need to build your own app to do so, and then you'll get an app identical to the Tabris.js app but with the plugins you specified, plus your JS code.

**Comment by natanraj** [comment]
Yeah, that is what i have been doing so far. But to play around quickly, I am leveraging ScratchPad more. May be am i missing something ?

**Comment by natanraj** [comment]
How to have/build my own developer app ?

**Comment by cookieguru** [comment]
Since Cordova plugins have code that access the native APIs, the code needs to be included in the binary that you install on your device.  There is no way to recompile the Tabris.js developer app through the app itself, so you have to [build](https://tabrisjs.com/documentation/latest/build) a new binary.
However, when you build a binary, if you [set debug on](https://tabrisjs.com/documentation/latest/build#settings) then you will get a full developer console plus the ability to load code from a URL.  Apps built in debug mode look almost identical to the Tabris.js developer app.  The only real difference is that the "My Scripts" tab is replaced with a "Bundled script" tab which contains the code that was in your repo when you started the build.

**Comment by natanraj** [comment]
Thanls. Getting some handle out of this. Now how to load the code from a URL ?...

Plus... Will the cordova plugins i added in my config.xml be also available by default ?

**Comment by cookieguru** [comment]
Loading your code from a URL in a custom-built debug app is identical to the Tabris.js developer app: Just flip over to the URL tab and type the URL in.

All the plugins you specify in `cordova/config.xml` and only the plugins you specify will be available.

**Comment by natanraj** [comment]
> Just flip over to the URL tab and type the URL in
I am not successful here. Trying to give https://github.com/natanraj/mytabris . This is the folder where my package.json is existing. But unable to establish connection to this URL

**Comment by cookieguru** [comment]
You can't just plug in the URL to your repo; the app tries (a few combinations) that results in things like `https://github.com/natanraj/mytabris/package.json`.  GitHub doesn't serve content directly from that URL, so the app is unable to load the JSON file telling it which file to load next (in your case, `js/home.js`) so it fails.
You _could_ give it `https://raw.githubusercontent.com/natanraj/mytabris/master/` which might work (I've never actually tried it).  However this means that you'd have to push your changes every time you adjust something in your code.

If you want to get in the write-test-deploy-repeat cycle, it's much easier if you can serve the code over HTTP from your development machine.  If you already have a webserver installed, place your code in a web-accessible directory.  If not, a quick way to get up and running is to `npm install -g httpserver`.  Once installed, just run `hs` from the same directory as your `package.json` and you'll instantly have a webserver running.  Take note of the available IP addresses and connect your device to the same network and just plug that URL in.

**Comment by natanraj** [comment]
I am somewhat ok now. the bundled script tab shows a 'undefined' row. which is my home.js. So that launched the app.

Also the My ScratchPad is able to access my Config.xml plugins. So all are functional to my expectation

**Comment by mpost** [comment]
@natanraj the answer from @cookieguru above to use the `httpserver` is the best way to have a quick and efficient code -> save -> reload cycle. It is highly recommended to serve your sources from your local machine once your project is more than just one file.

**Comment by jumpjack** [comment]
Any news about how to add plugins to developer app without recompiling?
Passing to the app the raw github link of my package.json results in "not found" (not found what? The [ur ](https://raw.githubusercontent.com/jumpjack/MyRenaultAndroid/main/package.json) works fine in the browser, as also it works the link to config.xml)

**Comment by cookieguru** [comment]
> Any news about how to add plugins to developer app without recompiling?

This will never be possible since it requires modifying the compiled bytecode and/or the manifest file which declares the necessary permissions

> Passing to the app the raw github link of my package.json results in "not found" (not found what? The [url](https://raw.githubusercontent.com/jumpjack/MyRenaultAndroid/main/package.json) works fine in the browser, as also it works the link to config.xml)

It is not recommended to use an internet link for this because:
1. none of the JS dependencies are available because the node_modules folder isn't there (this is why you're getting the 404)
2. a roundtrip across the internet is very slow compared to across your LAN
3. the correct MIME types are not served

**Comment by jumpjack** [comment]
Any other method to develop&debug an app which uses additional plugins, without installing anything on PC?

**Comment by cookieguru** [comment]
Cloud build works

**Comment by jumpjack** [comment]
> It is not recommended to use an internet link for this because:
> 
> 1. none of the JS dependencies are available because the node_modules folder isn't there (this is why you're getting the 404)
> 2. a roundtrip across the internet is very slow compared to across your LAN
> 3. the correct MIME types are not served

Is it "not recommended", or is "useless because it will never work in any case"?

I think I can totally disregard point 2, for debugging purposes;
Is the point 3 strictly mandatory?

About point 1: 
A) how should a github repo be set up to contain all needed files? 
B) If a github repo cannot be properly set up, can I setup a folder hosted on my remote server, in such a way that I should just upload my script to test it in tabris developer app? 

I don't want to setup a local environment for development, I need to be able to write and test code "on the cloud".
