### ISSUE TITLE
Need Placeholder For ImageView

### ISSUE THREAD

**Issue by jokorivai** [eclipsesource/tabris-js#1036]
Hi. I have code like so:
```js
var img = new tabris.ImageView({
	background: '#f8f8f8',
	scaleMode: 'fill',
	image: {src: xhr.baseUri+'images/006.jpg', scale: 1},
	layoutData: {left: 0, top: 0, right: 0}
}).appendTo(page);
```
As seen, `image.src ` is loaded from remote resource. When the image referred by this `image.src` is considered big (in size, let's say 2MB or something, we never now), the renderred ImageView is blank until loading process finished. If the loading process fails, the ImageView remains blank.
So it is necessary to add placeholder, say, like this:
```js
var img = new tabris.ImageView({
	background: '#f8f8f8',
	scaleMode: 'fill',
	image: {src: xhr.baseUri+'images/006.jpg', scale: 1},
	placeHolder: {'images/placeholder.jpg', scale: 1}, // from local assets folder
	layoutData: {left: 0, top: 0, right: 0}
}).appendTo(page);
```
Is this possible?
Thanks.

@mpost @cookieguru

**Comment by cookieguru** [comment]
Set your image to the local resource and use `ImageView`'s [`load`](https://tabrisjs.com/documentation/latest/api/ImageView#load-widget-event) event to then set it to the remote resource.  Example [here](https://github.com/eclipsesource/tabris-js/blob/1.x/snippets/imageview-load/imageview-load.js).

**Comment by jokorivai** [comment]
@cookieguru I tried that. The problem was, loading process never ended:
1. Set Image to local assets, this trigger `load` event, 2
2. Loading image from remote resource, when finish, will trigger `load` event, 2

So point 2 never end until the ImageView is disposed (with some error `object not found` on console)

I did made a check point to mark if the image had been loaded from remote resource, it worked. But for a lot of ImageView on different pages/modules, this is quite a  work. It is better to wrap this into TabrisJS code, so user can use the ImageView out of the box without too much additional code.

Thank you.

**Comment by cookieguru** [comment]
Maybe because it's late, but I don't quite follow.  If the problem is that the `load` event triggers twice, there are a few options around this; the first two that come to mind are:

1. When the `load` event fires, use the call `get()` on the first paramater of the callback to get the image source.  If it's the placeholder, set the image source to the remote URL.  Otherwise, handle the error
2. You can set arbitrary properties on any object, e.g. `image.set('placeholderLoaded', true);`.  You can then use that property to determine the widget's state.  Bonus: Tabris.js' property/event system will trigger an event for this, so you can listen for the `placeholderLoaded` event on the image and handle it accordingly.

If I'm misunderstanding let me know.

**Comment by jokorivai** [comment]
@cookieguru Yes I did that (point 2 of your comment). It worked. I just found out simpler solution TabrisJS already provided, as I added as edits to [my comment above](https://github.com/eclipsesource/tabris-js/issues/1036#issuecomment-260175820)
Thanks for supporting.
