### ISSUE TITLE
Allow to get more app metadata

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1053]
We should allow to get app specific metadata via the `tabris.app` object.

Properties of interest:

- `id` - Uniquely identifies an app on a users device.
- `version` - The user facing version number. Eg. '2.1-beta3'.
- `versionId` - Used in app stores to identify different versions of an app. Usually increment with each release.
- `tabrisJsVersion` - The Tabris.js release version of the native client. It is not not the Tabris.js version that the app developer provides in his `package.json` `tabris` dependency.

**Comment by mpost** [comment]
The following screenshot shows the properties in action in the `app.js` snippet:

![screenshot_1480591185](https://cloud.githubusercontent.com/assets/73655/20792128/8ca49b50-b7c0-11e6-9269-4c4949dee8c5.png)

**Comment by ralfstx** [comment]
The solution slightly differs from the proposal above:
- `versionId` renamed to `versionCode`
- `tabrisJsVersion` not implemented

**Comment by maoamid** [comment]
is it dangerous to use this mechanism to make environment variables available to js code?
Or how can I use some environment vars in my code (like api keys, others sensible data) ?

**Comment by cookieguru** [comment]
@maoamid How would you use this to make environment variables available to the JS code?  If you're referring to [the way the API key is added as an enviornment variable for the tabris maps plugin](https://github.com/eclipsesource/tabris-plugin-maps#android) that's actually designed to get the API key in to the Cordova config.xml so that the plugin builds correctly.

**Comment by maoamid** [comment]
@cookieguru Yes, you are right, that is what I was talking about. That is my question all about, how to make environment variables available to JS code, or if someone can suggest me a way to do this. I tried to figure it out if someone was thinking to a simple way to reuse the environment variables, other than for using them in cordova plugins, or do you know a simple plugin who can pass these variables to my JS code like a constant, in a global object let's say?

**Comment by cookieguru** [comment]
@maoamid Something like [this](http://stackoverflow.com/a/38509909)?

Note also, from [the docs](https://tabrisjs.com/documentation/latest/modules#script-modules):
> Implement each module as if there is no shared global scope
Rather than trying to manage globals you'd be better off creating a module to manage API access and then importing the module whenever you need it.  You can see an example of this design pattern in the [tabris-js-template-app](https://github.com/eclipsesource/tabris-js-template-app/tree/master/src/services).

**Comment by maoamid** [comment]
@cookieguru
I already use modules pattern for API, but I'm trying to find a way to encrypt my keys, so if that is done on build time, I think it's safer than anything. I don't know much about encryption, so the tabris way to encrypt environment variables seems a way it can be done.     I don't know if my way of thinking is right. Thank you for links, it help me a lot.

**Comment by cookieguru** [comment]
@maoamid Tossing API keys in an enviornment variable and having them integrated in to the app isn't encryption.  Even if you were to encrypt them inside the code of the app, your app would need to decode them to use them, and your decryption code would need to be part of the app as well.  In other words, security by obscurity.

Even if you were able to find a foolproof way to encrypt your API keys it would be moot since a determined user can always sniff the traffic between the app and a remote server.  I've used [Packet Capture for Android](https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture) to do exactly that.  Highly recommend the app next time you're looking to do some reverse engineering.

**Comment by maoamid** [comment]
@cookieguru, I see, thank you a lot for clarifications.
