### ISSUE TITLE
Tabris Plugin Firebase for Admob

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#1086]
Firebase for admob

**Comment by iteearmah** [comment]
:-)

**Comment by cookieguru** [comment]
There isn't enough information here to describe what the problem is.  If you're still having issues with these two plugins working together, please try my earlier suggestion on https://github.com/eclipsesource/tabris-js/issues/1083#issuecomment-270267836.

Since the [tabris-plugin-firebase](https://github.com/eclipsesource/tabris-plugin-firebase) and admob plugins each work on their own, compatibility with Tabris.js isn't an issue but rather it's an issue of compatibility with each other.

**Comment by mpost** [comment]
@cookieguru That would be correct. Having the two different strains of libraries will cause problems.

**Comment by iteearmah** [comment]
Hi, can you help with a sample app with the two implemented :-)

**Comment by mpost** [comment]
@iteearmah help will be hard to give. you should rely on one version only.

**Comment by mpost** [comment]
Closing this for now. Please target the https://github.com/eclipsesource/tabris-plugin-firebase for future issues.
