### ISSUE TITLE
Question - Date/Time input types

### ISSUE THREAD

**Issue by Zeldaze** [eclipsesource/tabris-js#1107]
Any suggestions on an easy to use date picker / time selector input type?
Will most likely have to use a Cordova plugin for that, right?

**Comment by cookieguru** [comment]
You are correct that there is no built-in date and/or time selectors in Tabris.js.  If you're looking for a calendar-based date selection, check out [tabris-calendar](https://github.com/eclipsesource/tabris-calendar).  It's Android-only because there is no equivalent native control on iOS.  I'd start with [cordova-plugin-datepicker](https://github.com/VitaliiBlagodir/cordova-plugin-datepicker) though I haven't tested it.

See also #652

**Comment by Zeldaze** [comment]
That's a shame, as I want to preserve cross-platform compatibility. Is
there no other option other than a series of pickers for the day/month/year
with some annoying logic to handle number of days per month?

**Comment by cookieguru** [comment]
The _calendar_-based plugin is Android-only.  [cordova-plugin-datepicker](https://github.com/VitaliiBlagodir/cordova-plugin-datepicker) is compatible with both iOS and Android.

**Comment by mpost** [comment]
We have also used the https://github.com/VitaliiBlagodir/cordova-plugin-datepicker in several projects and it served us reasonably well.

**Comment by cpetrov** [comment]
I will close this issue. Please reopen https://github.com/eclipsesource/tabris-js/issues/652 if you have any requirements which available Cordova plugins don't satisfy.

**Comment by cookieguru** [comment]
As of Tabris.js 2.2.0, the [DateDialog](https://tabrisjs.com/documentation/latest/api/DateDialog.html) and [TimeDialog](https://tabrisjs.com/documentation/latest/api/TimeDialog.html) widgets are available natively.
