### ISSUE TITLE
Javascript APi on Tabris.js

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1121]
Hello i have a question
Can i use 
Web Workers
Service Workers
Server Sent Event
IndexedDb
with Tabris.js?

**Comment by sand123** [comment]
Supported browser-inspired API documentaion is [here](https://tabrisjs.com/documentation/latest/w3c-api) - Persistent Storage one of them
Since stable version 1.10 Tabris.js supports WebSocket, so it's up to you which 3rd party plugin to use or you can recieve push notifications with [plugin](https://github.com/eclipsesource/phonegap-plugin-push) or even use [FireBase plugin](https://github.com/eclipsesource/tabris-plugin-firebase)
Eventually, you can use any cordova plugins with [some notes](https://tabrisjs.com/documentation/latest/cordova)
Also search for issues labeled with [cordova compatibility](https://github.com/eclipsesource/tabris-js/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3A%22compatibility%20cordova%22%20) to find info about cordova plugins that work with Tabris.js

**Comment by mpost** [comment]
@sand123 is absolutltly correct in his answer.

One more comment on Service Workers. At the moment they are not supported. If you need to do asynch/background work you should rely on a cordova plugin for that.

IndexDB is not supported but both iOS and Android support SQLite for which multiple cordova plugins exist.

**Comment by ishigo1987** [comment]
thank you very much
