### ISSUE TITLE
Custom themes in Tabrisjs 2?

### ISSUE THREAD

**Issue by bev-on** [eclipsesource/tabris-js#1147]
http://eclipsesource.com/blogs/2015/07/03/tabris-js-1-1-sneak-peak-custom-themes-on-android/

I was using this method successfully but now it's not working. No more custom theme options?

Also why not add ``colorPrimary``, ``colorPrimaryDark`` and ``colorAccent`` to ``tabris.ui``?

There can be ``tabris.ui.app`` or ``tabris.ui.general`` to set properties mentioned above

```
// something like this will be great
tabris.ui.app.colorPrimary = '#f00'
```

**Comment by mpost** [comment]
@bev-on We have update the names used to declare the custom theme. Otherwise the mechanism stays the same. Check the [2.0.0-beta1 release notes](https://github.com/eclipsesource/tabris-js/releases/tag/v2.0.0-beta1) (at the very bottom) and the [documentation describing the naming scheme](https://tabrisjs.com/documentation/latest/build#android-specific-preferences).

**Comment by mpost** [comment]
Regarding your second question... The colors you can set in the theme like primary, accent etc., are compiled into the theme during build time. The theme is then applied when a view is instantiated and there is no way to apply a new theme on an existing view. While it would be great to update the theme dynamically, this is the way the Android theme mechanics work. During run-time you can only change the properties that are exposed as regular API.

**Comment by bev-on** [comment]
Thanks @mpost. Already try to use DarkAppBar as parent, but I was getting error yesterday. I will try to again later and close this issue if there is no errors.

**Comment by mpost** [comment]
@bev-on Great. Let us know if you encounter any problems.

**Comment by bev-on** [comment]
@mpost is there any way we can help to improve/add documentation? There is no proper custom theme example and to be honest old blog post about custom themes is too complicated (and outdated as well) for people who don't have much experience with Cordova/Android.

I can write step by step instruction later if you can add it to documentation or blog.

**Comment by mpost** [comment]
@bev-on We should update the blog post for the 2.0.0 stable release when it is out. In the mean time you could contribute to the documentation here:

https://github.com/eclipsesource/tabris-js/blob/master/doc/build.md

Please keep it brief as this is designed to be a reference rather than a tutorial.

For the sake of getting into more into details we could create a new documentation page that picks up the content of the blog post and updated it to fit into the documentation as a new page that we link to from inside the reference docs.

**Comment by cookieguru** [comment]
+1 on centralizing the docs

**Comment by mpost** [comment]
We have updated the blog post on the topic to note the changes introduced in the Tabris.js `2.0.0-beta1`.

http://eclipsesource.com/blogs/2015/07/03/tabris-js-1-1-sneak-peak-custom-themes-on-android/

**Comment by mpost** [comment]
One thing that would tie in very well here is a mechanism to automatically include certain resources in the build without the need for a build hook. We will also look into this for the final `2.0.0` release.

**Comment by bev-on** [comment]
Thanks, I was able to set custom theme. I will close this issue and in near future I will try to publish code with custom theme and splashscreen examples.

**Comment by maoamid** [comment]
is this possible also for iOS systems?

**Comment by bev-on** [comment]
@maoamid only for Android.
