### ISSUE TITLE
question: settings hooks

### ISSUE THREAD

**Issue by maoamid** [eclipsesource/tabris-js#1192]
does Tabris.js 2 plan to support platform settings directly in cordova .xml? something similar with:
[https://www.npmjs.com/package/cordova-plugin-settings-hook](url) ?

**Comment by mpost** [comment]
@maoamid The plugin should work on iOS but it does not work on Android since the plugin maps several preferences to the cordova main Activity. With Tabris we use the cordova main activity to launch another activity which actually runs the tabris app.

https://github.com/mircoc/cordova-plugin-settings-hook/blob/master/updatePlatformConfig.js#L88

**Comment by cookieguru** [comment]
@mpost In that case what is the recommended way to slip entries in to `AndroidManifest.xml`?  E.g. [Samsung MultiWindow](http://developer.samsung.com/galaxy/multiwindow)

**Comment by mpost** [comment]
@cookieguru You can use a custom build hook that addresses the activity `TabrisActivity` in the AndroidManifest.xml instead of the `MainActivity` that cordova contributed.

**Comment by maoamid** [comment]
@cookieguru Another simple way is to create a simple cordova plugin to edit it, I didn't know how to use build hooks yet

**Comment by ralfstx** [comment]
@maoamid I hope your question is answered, please reopen if not.

**Comment by maoamid** [comment]
@ralfstx yes it is, thanks
