### ISSUE TITLE
Can't see images after build!

### ISSUE THREAD

**Issue by FrencoJobs** [eclipsesource/tabris-js#1205]
Everywhere of images are blanks,I can't see my images.It's OK in debugging app and in playground app.The file path is right.

**Comment by mpost** [comment]
Could you provide some more details? Platform, Build settings, Image paths.

**Comment by FrencoJobs** [comment]
Platform - Android
Build Settings - Defaults
Debugging Mode off,
Signing key and Release Key - Defaults
Images paths - `src/images/`

**Comment by bFlood** [comment]
check that your image paths are case sensitive, I think it works either way in debug but is case sensitive in release

**Comment by mpost** [comment]
There is no difference between debug and release builds when it comes to image location resolving. Are you sure your images are bundled in the app?

**Comment by cpetrov** [comment]
@FrencoJobs How do you reference the image location in [ImageView.image](https://tabrisjs.com/documentation/latest/api/ImageView#image)?

For built apps, image path will always be resolved relative to the location of `package.json`.

i.e. if you have the following project structure:

```
package.json  
images
|-- myImage.png
src
|-- main.js    
```
... and you create the `ImageView` in main.js, you should use:

```js
new ImageView({image: 'images/myImage.png'}); // or
new ImageView({image: '/images/myImage.png'});
```

instead of:

```js
new ImageView({image: '../images/myImage.png'}); // won't work!
```

**Comment by FrencoJobs** [comment]
@cpetrov Thanks.That's work now by your answer.
Thanks a lot.
