### ISSUE TITLE
Suggestion to win the popularity contest

### ISSUE THREAD

**Issue by kokizzu** [eclipsesource/tabris-js#1218]
The Problem with ReactNative is.. they didn't include "Web" part within, they only focusing on "Mobile" part (although there are some [alternative](https://github.com/necolas/react-native-web) but not fully supported). If TabrisJS want to win the popularity against ReactNative, there should be integration with the "Web" part, single codebase for those 3 platform (or 4: with desktop via electron).

**Comment by cookieguru** [comment]
There are actually three platforms already since as of Tabris.js 2 apps can be deployed to Windows 10 devices (PC, tablet, phone, Xbox, and more).

The framework itself is open source, and as has been mentioned in #966 and #961 there's nothing stopping anyone from adding additional web or desktop clients.  Given the state of [the roadmap](https://tabrisjs.com/grand-central) and the number of open issues I think the team has plenty to work on with the three existing platforms and any new ones would probably be best served by the community at this time.

**Comment by mpost** [comment]
@kokizzu You are right about your statement. We strongly believe in the platforms we currently support but are always open to support new platforms. The web is of course an interesting choice and would be well suited for Tabris.js

As of now i am closing this issue.
