### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1230]
Hello How to get an error report when my build fail?

**Comment by cookieguru** [comment]
Post the full output of the build log somewhere and link it here.

**Comment by ishigo1987** [comment]
[log.txt](https://github.com/eclipsesource/tabris-js/files/909255/log.txt)

**Comment by ishigo1987** [comment]
this is my log file

**Comment by ralfstx** [comment]
> Error: Error validating package name. Package name must look like: com.company.Name

That's the app id in your `cordova/config.xml` file. Look for (`<widget id="...")`. This id must be a valid Java package name and it must have a period in its name. The current version of the CLI ensures this pattern.

**Comment by cookieguru** [comment]
> Error: Error validating package name. Package name must look like: com.company.Name

The `id` attribute in the root `widget` tag of `cordova/config.xml` needs to be in reverse-domain notation, like `org.example.myapp`

**Comment by ishigo1987** [comment]
after the compilation i install the apk and i see this
![screenshot_2017-04-10-10-09-08](https://cloud.githubusercontent.com/assets/12398336/24854408/4594338e-1dd6-11e7-8f3e-74b348b83725.png)
Why i'm still into a tabris container and not directly into my app?

**Comment by cookieguru** [comment]
Because you built a debug version of your app.  This contains all of your Cordova plugins plus the source code from your repo at the time you built it. If you need to make changes to your source code you can do so on your development machine and load them via the URL tab. 

Once you perform a Release build you will no longer have any of the developer tools and your app will launch straightaway.

**Comment by ishigo1987** [comment]
ok thank you
