### ISSUE TITLE
tabris-maps-plugin errors during android build

### ISSUE THREAD

**Issue by capotti** [eclipsesource/tabris-js#1308]
[errors.txt](https://github.com/eclipsesource/tabris-js/files/992631/errors.txt)
create a new project with `tabris init`
edit cordova/confix.xml
insert
```
<plugin name="tabris-plugin-maps" spec="https://github.com/eclipsesource/tabris-plugin-maps.git">
        <variable name="ANDROID_API_KEY" value="blablablubb" />
</plugin>
```
`tabris build ios`
works.

`tabris build android`
results in errors:
```
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/dirk/Documents/workspace/apps/teschd/build/cordova/platforms/android/src/com/eclipsesource/tabris/maps/MapCameraChangeListener.java:3: error: cannot find symbol
import com.eclipsesource.tabris.android.ObjectRegistry;
```

**Comment by natanraj** [comment]
@capotti what is your version in dependencies package.json ? I guess tabris.js is team is doing quite amount of trial with beta2 and maps and fcm which is posing sufficient challenges.

**Comment by capotti** [comment]
```
  "dependencies": {
    "tabris": "^2.0.0-beta2"
  },
  "devDependencies": {
    "eslint": "^3.19.0"
  }
```
tested with "nightly" version also.

An installable version for development would be great - has not to be production state ;-)

**Comment by cookieguru** [comment]
I'm using this `package.json`:
```json
{
  "dependencies": {
    "tabris": "nightly"
  }
}
```
And this `config.xml`:
```xml
<?xml version='1.0' encoding='utf-8'?>
<widget>
	<plugin name="tabris-plugin-maps" spec="https://github.com/eclipsesource/tabris-plugin-maps.git">
		<variable name="ANDROID_API_KEY" value="..." />
	</plugin>
</widget>
```
I built using the Cloud build service yesterday; works great.

**Comment by capotti** [comment]
@cookieguru 
ok, let me adopt my environment to the cloudservice environment
What versions are used / recommended:

- node version
- cordova version
- tabris version
- android sdk version

**Comment by cookieguru** [comment]
I used Tabris.js `2.x-nightly` for the build.  None of the others matter.  I don't have Cordova nor the Android SDK installed.  Since Node was only used to run `npm install` its exact version is not likely to be super relevant.

2.0 RC1 [was released yesterday](https://eclipsesource.com/blogs/2017/04/25/tabris-js-2-0-rc1-is-here/) so you could use that as well.  Regardless of which version you use, just make sure you keep the version in your `package.json` in sync with the version you use to build the app.

**Comment by capotti** [comment]
@cookieguru 
Strange. I try with build service and get the same error.
![bildschirmfoto 2017-05-13 um 00 22 29](https://cloud.githubusercontent.com/assets/28459193/26019150/ab6dd03c-3773-11e7-8df7-75b8689a4b60.png)


I downloaded the created apk and opened in the android emulator (Android 4.2, Android 5.0)
**app.js**
```javascript
new esmaps.Map({
	  left: 0, right: 0, top: "50%", bottom: 0
	}).on('ready', function() {
	  // show paris with a radius of 2000 meters
	  this.moveToPosition([48.8644458, 2.3589976], 2000);
}).appendTo(tabris.ui.contentView);
```

**config.xml** contains
```
    <access origin="*" />
    <plugin name="tabris-plugin-maps" spec="3.0.0">
        <variable name="ANDROID_API_KEY" value="blablablubb" />
    </plugin>
```

Repository: https://github.com/capotti/tabritest

**Comment by cookieguru** [comment]
When you specify a plugin by name/spec it's going to grab that package+version [on npm](https://www.npmjs.com/package/tabris-plugin-maps).  3.0.0 hasn't been published.  I bet if you look at your build log it will show the plugin failed to install, which is why `esmaps` is undefined.  This is annoying, a known issue, and totally in the hands of the Cordova team: #1148

Instead, specify the git url as specified in [the other example](https://github.com/eclipsesource/tabris-plugin-maps#add-the-plugin-to-your-project).  This is a doc bug and will probably be fixed on Monday.

BTW only the 3.*.* releases are compatible with Tabris.js 2, so you'll want to avoid >2.0.1

**Comment by capotti** [comment]
![bildschirmfoto 2017-05-13 um 00 41 46](https://cloud.githubusercontent.com/assets/28459193/26019345/0aac2458-3775-11e7-8eaa-78a199024237.png)

**Comment by capotti** [comment]
**changed into**
```
    <plugin name="tabris-plugin-maps" spec="https://github.com/eclipsesource/tabris-plugin-maps.git">
        <variable name="ANDROID_API_KEY" value="blablablubb" />
    </plugin>
```

**Local build**
/Users/dirk/Documents/workspace/apps/tabritest/build/cordova/platforms/android/src/com/eclipsesource/tabris/maps/MapCameraChangeListener.java:3: error: cannot find symbol
import com.eclipsesource.tabris.android.ObjectRegistry;
                                       ^

**build service**
app displays a map - (without content - evtl. the can't get internet connection?
google maps is installed also and works fine... maybe I have to grand access in a special way...)

**Comment by cookieguru** [comment]
Sounds like your Cordova platform is either out of date or not installed.

https://tabrisjs.com/documentation/latest/local-build#downloading-tabrisjs-platforms

**Comment by capotti** [comment]
(by the way - I suppose - map-plugin cannot display data - because my API-KEY is just fake...)

**Comment by cookieguru** [comment]
> package.json does not work alone. Tabris platform folder with other components had to be renewed as well?

The JS framework and the native code (which is what you get in the Cordova platform) are developed in parallel.  You should update one at the same time you update the other.
