### ISSUE TITLE
Allow different cell types on the same CollectionView

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#131]
There are a lot of use cases where not every item in a list has the same basic layout. For example your first or last item may allow adding/removing/frefresh, or you may have in-between headings. It might also be nice to have the last heading stay fixed on top of the List. 

Note that it is not a good solution to build your own List to achieve these effects. I tried, but iOs get's VERY slow after just a few dozend items. See http://floriankugler.com/blog/2013/4/21/auto-layout-performance-on-ios

**Comment by ralfstx** [comment]
Here's a draft for a protocol change to implement cell types:

#### Native Bridge Protocol
In order to create the right number of items for different types, the native clients have to request the type for each item. For proper layouting, they also need to know the height of every item. They do so by sending an *event* named `requestCellDescription` with an `index` parameter that contains the index of the item which description is requested.

The JS side “answers” by sending a *call* operation `describeCell` with parameters `index`, `type`, and `height`. The `type` is represented by a sequentional integer number, starting from `0`. If the JS side does not answer during the event processing, the native clients must fall back to `0` for the `type` and to the CollectionView's `itemHeight` property for the `height`.

When creating new reusable items, the native clients must specify the cell type by adding a parameter `type` to the `createItem` event.

**Comment by ralfstx** [comment]
Two issues with the current names:

- events in Tabris.js are all lowercase, we should stick to this scheme
- the current CollectionView protocol uses the term "item" instead of "cell"

Therefore I'd suggest to rename:

- `requestCellDescription` to `requestinfo`
- `describeCell` to `describeItem`

**Comment by jordiboehmelopez** [comment]
`requestinfo` all lower case? Or camelCase?

**Comment by mpost** [comment]
+1 for "item" name but juding from the above comment the `decribeItem` should be `describeitem`.

**Comment by ralfstx** [comment]
@jordiboehmelopez All events in Tabris.js are lowercase for compatibility with DOM events.

**Comment by ralfstx** [comment]
@mpost `describeItem` is a *call*, not an event. Those are usually camelCase.

**Comment by mpost** [comment]
makes sense i guess.

**Comment by ralfstx** [comment]
Renamed as suggested in the latest patch set of the draft in Gerrit https://gerrit.eclipsesource.com/#/c/5337/
