### ISSUE TITLE
bug new tabrisJs Developper app

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1318]
The new Tabris developper app is filled with bug nothing works.
this snippet return null
 const plateformeLanguage = tabris.device.get("language");
All my code that worked before return errors right now
It's really frustrating
![screenshot_2017-05-15-10-15-48](https://cloud.githubusercontent.com/assets/12398336/26050823/0a62b414-3958-11e7-9192-e61423707196.png)
![screenshot_2017-05-15-10-16-01](https://cloud.githubusercontent.com/assets/12398336/26050833/16617e6c-3958-11e7-8130-edfc6c358577.png)
 console.log(plateformeLanguage);

**Comment by ralfstx** [comment]
Please help us fixing your issue by providing some information:
- Which version of the developer app do you use?
- Which tabris version do you have in your package.json?
- Did you `npm update tabris` lately?

**Comment by ishigo1987** [comment]
TabrisJs version 2.0.2-20170505-1053(12 may 2017)
in my package json i have 2.0.0-beta2
No npm update lately

**Comment by ralfstx** [comment]
Since your developing against the development stream, you now have to update to tabris `2.0.0-rc1` (replace version in `package.json` and call `npm update tabris`) and adjust your app to the recent API changes.

See also:
- http://eclipsesource.com/blogs/2017/04/25/tabris-js-2-0-rc1-is-here/
- https://github.com/eclipsesource/tabris-js/releases/tag/v2.0.0-rc1

**Comment by ishigo1987** [comment]
where should i type npm update tabris inside my project folder?

**Comment by ishigo1987** [comment]
ok i fixed the problem thank you
