### ISSUE TITLE
WebView bugs and 3rd party usage

### ISSUE THREAD

**Issue by capotti** [eclipsesource/tabris-js#1344]
(1) I created a 3rd party widget to display html structured content in an easy way - see
https://github.com/camindo/camindo-tab-widget-html
Please check if references to tabris.js are according to your policies.

(2) the widget uses a WebView.
Please check bugs, discribed under ["Layout Notes"](https://github.com/camindo/camindo-tab-widget-html#layout-notes)

![rotationbug](https://cloud.githubusercontent.com/assets/28459193/26279395/d281b950-3db2-11e7-8b66-cde000f2fcd6.png)

**Comment by karolszafranski** [comment]
I would not say that this is a bug. These two web engines behave in a different way. You can read about `viewport` on iOS here: https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/UsingtheViewport/UsingtheViewport.html

Additionally basing on this thread: http://stackoverflow.com/questions/7892809/viewport-meta-tag-for-ios-devices 

If you set: `<meta name="viewport" content="width=device-width">` This means: "width of the viewport is equal to device width", and device width is orientation independent. It means that iPhone 5S width is always 320pt, doesn't matter if you look at it in portrait or in landscape. 

Key to understand that is a prefix `device`, we don't refer to screen, window, or view, these might be considered as changing their width on rotation, but device itself is not.

Of course it's a matter of interpretation, and that's why browsers behave in a different way, but I would compare it to example: if you are standing straight you are 180cm tall, and if you lay down on the floor you are still 180cm tall. So your height is always 180cm - orientation independent.

Some may like it, some not, but for some reason this is how it works on iOS.

You should try:
- As suggested on StackOverflow add `maximum-scale=1` to the viewport.
- Set width equal to strict number - width of the widget. Maybe update this tag with data taken from `resize` event?

**Comment by capotti** [comment]
Hello @karolszafranski thanks for detailed answer!! It sounds plausible.
But it does not fit Apples own definitions.

* iOS Safari refreshes the layout on rotation - if the mentioned meta-tag is used.
* a plain cordova app refreshes the layout on rotation. The following meta-tag is used: 
 ```<meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">``` 
 If I use the same meta-tag, the layout is not refreshed in tabris webView - just scaled
* if device-width and device-height would be swaped on rotation on iOS - then following meta-tag should have to work in landscape mode: 
 ```<meta name="viewport" content="........., width=device-height">``` 
 but in a tabris webView the content is still scaled.

Yes, I will find a workaround as you described - resize the webView on rotation. But I'd rather have **native** functionality that works as expected - at least cordova like behaviour.
If there is an update - please inform me.
Thanks for help!

**Comment by karolszafranski** [comment]
This is web engine behaviour, so everything based on `WKWebView` and `UIWebView` should behave in same way.
