### ISSUE TITLE
Opening the keypad is not resizing to focus on the Input Field

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1355]
### Problem description

- Actual Behavior: Having a button at the bottom of the screen and few input text fields above. 

When the field is pressed, the keypad opens, but the button overlays on the Text Fields, unable to see focused Field
- Expected Behavior: The screen resize should focus on the Input field for which the keypad is opened

### Environment

- Device (name and OS version): Redmi, android
- Tabris.js version: 2.0.0-RC1

### Code snippet

```javascript
// myPage is a variable to my Page.

let txName = new tabris.TextInput().appendTo(myPage);
txName.layoutData = {top:200, centerX:0, width: 200};
let txArea = new tabris.TextInput().appendTo(myPage);
txArea.layoutData = {top:'prev()', centerX:0, width: 200};
let myUserActionsContainer = new tabris.Composite({background:'green'}).appendTo(myPage);
myUserActionsContainer.layoutData = {bottom:0, centerX:0, width:100, height: 100};
```

**Comment by mpost** [comment]
I have refactored your snippet a bit to show your described behavior:

```js
new tabris.TextInput({
  top: 200, centerX: 0, width: 200
}).appendTo(tabris.ui.contentView);

new tabris.TextInput({
  top: 'prev()', centerX: 0, width: 200
}).appendTo(tabris.ui.contentView);

new tabris.Composite({
  bottom: 0, centerX: 0, width: 100, height: 100,
  background: 'green'
}).appendTo(tabris.ui.contentView);
```

This leads to the following expected layout when the keyboard is opened:

![screenshot_1496309137](https://cloud.githubusercontent.com/assets/73655/26673422/20a0840a-46bd-11e7-9854-6898082775ab.png)

Since the entire `tabris.ui.contentView` resizes you have full control how your layout should present itself when the `contenView` size changes.

**Comment by ralfstx** [comment]
@natanraj I'm closing this issue as it seems to work as expected. The UI is relayouted according to the layout data in your code. Please re-open if you need further help.
