### ISSUE TITLE
Gesture interaction affect to sub-level widgets

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#1357]
# Problem description

- Actual Behavior: Any interaction with top-level widgets affects to sub-level widgets as well. 
- Expected Behavior: Sub-levels widgets must not be affected by any interaction that occurred on top-level widgets. 

# Environment

- Device (name and OS version): Nexus 6P, Android 7.1.2
- Tabris.js version: 2.0.0-rc1-dev.20170425

# Code snippet

```
import {NavigationView, Page, Composite, ui} from 'tabris';

let navigationView = new NavigationView({
  left: 0, top: 0, right: 0, bottom: 0
}).appendTo(ui.contentView);

let page = new Page().appendTo(navigationView);

new Composite({class: 'red', left: 10, top: 10, right: 10, bottom: 10, background: 'red'})
  .on('tap', () => console.log('is tapped!!!'))
  .appendTo(page);

new Composite({class: 'yellow', left: 0, top: 0, right: 0, bottom: 0, background: 'yellow'})
  .appendTo(ui.contentView);
```

In that snippet, when we tap on yellow composite, 'is tapped!!!' is printed to the console. However, tap handler of red composite must not be called.

**Comment by cookieguru** [comment]
Related: #1105

**Comment by mpost** [comment]
The behavior is as expected. Refactoring the snippet slightly to be runnable standalone:

´´´js
let navigationView = new tabris.NavigationView({
  left: 0, top: 0, right: 0, bottom: 0
}).appendTo(tabris.ui.contentView);

let page = new tabris.Page().appendTo(navigationView);

new tabris.Composite({
  left: 10, top: 10, right: 10, bottom: 10,
  background: 'red'
}).on('tap', () => console.log('red is tapped'))
  .appendTo(page);

new tabris.Composite({
  left: 20, top: 20, right: 20, bottom: 20,
  background: 'yellow'
}).appendTo(tabris.ui.contentView);
´´´

The following layout is created from the snippet above:

![screenshot_1496309536](https://cloud.githubusercontent.com/assets/73655/26673658/fba5c628-46bd-11e7-9458-4b540668d7ba.png)

What you can see here is that the yellow `Composite` is placed above the the `NavigationView`. Since the only the red `Composite` inside the `NavigationView` has a tap listener the yellow `Composite` does not intercept any touches. You will need to add a listener to the yellow `Composite` to intercept the touch events.

**Comment by mpost** [comment]
Closing as "works as expected".
