### ISSUE TITLE
TextEncoder & TextDecoder support

### ISSUE THREAD

**Issue by jonaspm** [eclipsesource/tabris-js#1410]
[FEATURE REQUEST]

### Problem description

The new filesystem API is nice, but encoding/decoding files should be straightforward as the rest of the Tabris.JS ecosystem

### Expected behavior

easy encoding / decoding files thanks to TextEncoder / TextDecoder.

### Environment

- Tabris.js version: 2.x.0
- Device: ---
- OS: Android, iOS

### Code snippet

```javascript
let bytes = new Uint8Array([72, 101, 108, 108, 111 ,32, 87, 111, 114, 108, 100, 33]);
let decodedString = new TextDecoder('utf-8').decode(bytes);
console.log(decodedString); // Hello World!

let encodedString = new TextEncoder().encode(decodedString)
console.log(encodedString) // Uint8Array
```

There is a shim available on npm:
https://github.com/inexorabletash/text-encoding

Spec:
https://encoding.spec.whatwg.org/

**Comment by ralfstx** [comment]
We will definitely provide support for text files. However, the TextEncoder/TextDecoder APIs doesn't seem to be suited best for Tabris.js, as they're synchronous. Since application code is executed in the UI thread, it has to be very fast to avoid causing hickups in animations etc. Decoding larger strings will probably take too long to fit into a single frame.

We already have an asynchronous TextDecoder implementation and we might expose this or add encoding options to the fs API similar to Node.js.
