### ISSUE TITLE
Widget touch listeners are not operational when native keyboard is open

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#1462]
### Problem description

The issue can be reproduced with the snippet below. The snippet contains a text input and a button that is positioned at the bottom. 

When I tap to the text input, the native keyboard opens and I start to type something. As soon as I finish my writing, I want directly click on the button. However, my first `click` attempt does not affect to the button(My first `click` attempt causes the closing of the native keyboard). Afterward, my second `click` attempt affects to button.

### Expected behavior

My first `click` attempt must affect to the button as well.

### Environment

- Tabris.js version: 2.0.0-dev.20170718
- Device: Iphone 6
- OS: iOS 10.3.3

### Code snippet

```javascript
import {Button, TextInput, ui} from 'tabris';
let count = 0;
new TextInput({
  left: 16, top: 16, right: 16,
  message: 'Input'
}).on('select', ({target}) => target.text = 'Pressed ' + (++count) + ' times')
  .appendTo(ui.contentView);
new Button({
  centerX: 0, bottom: 16,
  text: 'Button'
}).on('select', ({target}) => target.text = 'Pressed ' + (++count) + ' times')
  .appendTo(ui.contentView);
```

**Comment by mpost** [comment]
I can not confirm the described behavior. Works as expected on Nexus 6P, Android Emulator and Samsung Galaxy J3.

**Comment by patrykmol** [comment]
At the moment it is unclear how we should fix the problem. Cause for this is the gesture recognizer to fire it's event on touch down instead of touch up (release). When text input is focused and user taps on a button, button receives touch down event. At the same time `CancelKeyboardRecognizer` is fired causing keyboard to hide. Button is moving to the bottom of the screen and then the finger is released. Finger release happens after button has already moved therefore touch up (release) event is outside of button and the press is canceled. Proper fix would be to fire this event on finger release from screen however it did not work when tested. Other fix would be to use touch down event for button instead of touch up (release) but this way we won't have ability to cancel press.

Current workaround is to use label with touch listener.
