### ISSUE TITLE
Why is min SDK version for Android, 4.2 or API 17?

### ISSUE THREAD

**Issue by ohenepee** [eclipsesource/tabris-js#1500]
Does anyone know exactly why the minimum SDK version for Android is now 4.2+? Could it have anything to do with a particular Android component?

I am developing for users who will mostly be using 4.0+ devices, but I also want the awesomeness of v2.x as well

**Comment by bev-on** [comment]
@ohenepee 4.0+ doesn't necessarily means 4.0 or 4.1.

I checked my website statistics and I can't find single visitors with <4.3 version of Android for last 3 months (and I have some visitors still using IE 8).

Most of 4.1 devices (even cheapest Chinese brands) were updated to 4.2 and 4.3 since they all are part of code name Jelly Bean.

Android 4.0 was released 6 years ago and 4.1 was released 5 years ago. It means that if user still using device with this versions of Android, it will be minimum 5 years old and it was very cheap device because it didn't get new updates... and devices like this don't last for 5-6 years anyway.

Moral is that don't use older Tabris.js versions because of potential 0.1% users. Most popular 4.x Android is 4.4.4 (Kitkat) and it's fully supported in Tabris.js 2.0 (except few minor issues like tint).

Maybe if you or your friends have website in your target region, check Google Analytics OS statistics and you will see that I'm right.

**Comment by ohenepee** [comment]
@bev-on thanks for the insight. But unfortunately you're wrong on almost everything, Aside Europe and the US, the rest of the world have a lot of 4.0-4.1.2 devices... and no, 90% of these devices were never updated by their manufacturers OTA... and we're not talking about cheap and inferior Chinese devices. I typed this message from a Motorola Droid RAZR XT912 which is running 4.1.2. Also use Google Analytics to check third world regions and see for urself. But I'm not really looking for advice, I just want to know what I can omit to get Tabris.js 2.0 to run on 4.0+ devices without try-and-error

**Comment by mpost** [comment]
We have dropped support for Android 4.0 and 4.1 because it is technically hard to maintain when going forward. We use the official Android version distribution charts when deciding on the minimum supported version: https://developer.android.com/about/dashboards/index.html. As you can see in the chart, we dropped 5 percent of potential users, leaving 95% still in tact.

**Comment by cookieguru** [comment]
@ohenepee For info on which APIs have changed, see this link:
https://developer.android.com/about/versions/android-4.2.html
