### ISSUE TITLE
scrollview and tabfolder

### ISSUE THREAD

**Issue by gacal** [eclipsesource/tabris-js#1505]
tabFolder not working

### Environment

- Tabris.js version: 2.1.0
- Device: xiaomi 5 
- OS: android 7

### Code snippet

```javascript

    let userTab = new TabFolder({
        layoutData:{left: 0, top: 'prev() 20', right: 0},
        paging:true
    }).appendTo(container);

    let otherImg = new Tab({
        title:'Fotoğraflar'
    }).appendTo(userTab);
    //otherImg.append(ImgContainer);

    let userInfo = new Tab({
        title:'Detaylar'
    }).appendTo(userTab);

    let about = new TextView({
        text: 'ısf oasıf sodıfjsopdıfj asodpıfjodsdofadsoıf joıfjsoıfjosaı faodfjo ıfjspodıjfa oıdfj dfasdfsdf asdfasf sdfs dfas dfsdf sadf sf sd fasdf fadfadsfa a',
        font: '16px',
        textColor: '#555',
        layoutData: {left: 10, right: 10,top:'prev() 0'},
        alignment: 'left'
    }).appendTo(userInfo);

```
![untitled-5](https://user-images.githubusercontent.com/3254134/31198719-e5825598-a95d-11e7-87c5-13df212aa10d.jpg)

**Comment by mpost** [comment]
Running your provided snippet yields the following results which are correct in terms of the snippet layout.

![screenshot_1507191188](https://user-images.githubusercontent.com/73655/31217051-fa219fe2-a9b5-11e7-8683-88bba8cc42dd.png)

Since the `TabFolder` is not constrainted to a specific height you are not seeing the content of the `Tab`. You should provide a `bottom: 0`. on the TabFolders layoutdata to span the `TabFolder` to get the following result:

![screenshot_1507191257](https://user-images.githubusercontent.com/73655/31217163-48dd903c-a9b6-11e7-98b9-90d9b16cfe4d.png)

Please also see the TabFolder snippet: https://github.com/eclipsesource/tabris-js/blob/master/snippets/tabfolder.js

**Comment by mpost** [comment]
Closing the issue was not intended. Please reopen if you could not solve your problem.
