### ISSUE TITLE
Resize event parameters of the ui#contentView are incorrect

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#1524]
### Problem description

When we set resize event listener for the ui#contentView, we get incorrect height and width values which is 0. 

### Expected behavior

We must get real size values for the resize event of the ui#contentView.

### Environment

- Tabris.js version: 2.1
- Device: iPhone 6
- OS: 11.0.2

### Code snippet

```javascript
const {Composite, ui} = require('tabris');

new Composite({
  left: 0, top: 0, right: 0, bottom: 0,
  background: 'yellow'
}).appendTo(ui.contentView);

ui.contentView.on('resize', ({width, height}) => console.log('width: ' + width + ' height: ' + height));
```

**Comment by bev-on** [comment]
@elshadsm this is very annoying on iOS, many events are triggered on "event start" instead of "event end" and this makes cross platform development painful since Android triggers events after "event end" (which is correct way).

 As temporary fix, you can use setTimeout and wait few milliseconds before you get updated size.

```
const {Composite, ui} = require('tabris');

new Composite({
  left: 0, top: 0, right: 0, bottom: 0,
  background: 'yellow'
}).appendTo(ui.contentView);

ui.contentView.on('resize', () => {
  setTimeout(() => {
    console.log('width: ' + ui.contentView.bounds.width + ' height: ' + ui.contentView.bounds.height);
  }, 100);
});
```
Instead of 100ms, you can set any amount you want since it even works with 1ms, but to be safe on older devices, don't make it lower than 100ms.

**Comment by mpost** [comment]
@bev-on @elshadsm Luckily in the case the bug has been fixed and will roll out in the next Tabris.js release. :)
