### ISSUE TITLE
get access to cordova plugin javascript

### ISSUE THREAD

**Issue by truthSeekr** [eclipsesource/tabris-js#1552]
### Problem description

I try to use cordova plugin(https://github.com/katzer/cordova-plugin-background-mode) in my first tabris app.

I added 
`<plugin name="cordova-plugin-background-mode" spec="https://github.com/katzer/cordova-plugin-background-mode" />`
to my `cordova/config.xml` file

and in my `www/app.js` I try to 
`cordova.plugins.backgroundMode.isActive();`
and it returns "cannot read property 'isActive()' of undefined

YES, I made build locally, my sdk is 25. The build is made successfully. Then I use `tabris serve` and developer app.

What am i missing ?
### Environment

- Tabris.js 2.1.3
- Device: HUAWEI(Android) - SDK 25

**Comment by cookieguru** [comment]
The advice on https://github.com/eclipsesource/tabris-js/issues/831#issuecomment-273421648 still stands.  Since then, Android 8.0 has been released and even further restricts background tasks.

On your other issue you mentioned you built with gradle.  Are you using [`tabris build android`](https://tabrisjs.com/documentation/latest/build#local-build) or something else?

**Comment by truthSeekr** [comment]
yes, `tabris build android`. Thanks for your time. Maybe I should check then some other cordova plugin.

**Comment by cookieguru** [comment]
Try the aforementioned barcode scanner plugin to get your feet wet.  Then you might want to look in to [tabris-plugin-firebase](https://github.com/eclipsesource/tabris-plugin-firebase).

**Comment by truthSeekr** [comment]
as it is default `cordova.plugins.barcodeScanner.scan(successCallback, errorCallback);` fires with no problem

**Comment by cookieguru** [comment]
It is a "default" plugin in the sense that it is bundled with the Tabris.js Developer App distributed in the app stores.  When you build your own app, it is *not* included unless you _specifically_ add that plugin to your `config.xml`.

**Comment by cookieguru** [comment]
If you didn't add the barcode scanner plugin to your `config.xml` and `cordova.plugins.barcodeScanner.scan` is defined in the app you built, it means you haven't installed the APK on your device.  That is the purpose of the build--to create a new APK.  Building is not necessary for only JS changes.

**Comment by truthSeekr** [comment]
Lol so maybe this is my missunderstanding. So If I want to use some custom plugins then I cant use developer app to check results ? I mean i build it locally so how tabris serve works then ?

**Comment by cookieguru** [comment]
`tabris serve` starts a webserver to serve up your JS code so you can instantly reload.  When you run `tabris build android` it will generate a new APK file that you need to install on your device.  If you didn't do that, it would explain why the objects are undefined in JS.

Plugins add code that accesses native device APIs.  This code cannot be updated "on the fly" like JS and has to be compiled in to the binary.  When you are adding or removing plugins, you will need to build and then install the new binary.  To test your JS code, you can simply use the reload button from the app.  When you feel like you have a release candidate, you will then build your app in _production_ mode instead of debug and the developer console will no longer be included and the binary will ship with the JS code that existed when you built the app.

**Comment by truthSeekr** [comment]
Ok but if I will generate my own APK i cant use from here JS "on the fly". Because i dont have that component that is in developer app. Is there developer app somewhere on github that i can rebuild and use "javascript on the fly"  from there ? Thanks for your time

**Comment by cookieguru** [comment]
If you build with [`EnableDeveloperConsole`](https://tabrisjs.com/documentation/latest/build#preferences) set to `true` then your built app will have the debug console where you can specify the URL from `tabris serve`.

**Comment by truthSeekr** [comment]
Thanks a lot. And because of  https://github.com/eclipsesource/tabris-js/issues/831#issuecomment-273421648 I kindly lose temper to use it. Do you know some better way to keep application working in the background ?

**Comment by cookieguru** [comment]
Depends on what your use case is.  [tabris-plugin-firebase](https://github.com/eclipsesource/tabris-plugin-firebase) might work.

**Comment by truthSeekr** [comment]
firebase its too complex for me. I want simply to make my app working in background mode

**Comment by cookieguru** [comment]
What do mean by "work"?

**Comment by truthSeekr** [comment]
When i have open aplliication for example tabris dev app. When i put(for ex. tabris app dev) into background mode for few minutes, when im back to tabris, it needs to reload. It happens after few minutes. I want to prevent app from geting to sleep

**Comment by cookieguru** [comment]
@truthSeekr That's an OS feature to conserve battery power.  If you bypassed that, your app would use a considerable amount of resources which would upset your users.

Instead, you should listen for the [`pause`](https://tabrisjs.com/documentation/latest/api/app.html#pause) or `terminate` events and save the application state.  Then you can listen to the `resume` and `foreground` events to restore the state.

For small bits of data [`localStorage`](https://tabrisjs.com/documentation/latest/api/localStorage.html) should be sufficient.  For larger datasets you may need [`fs`](https://tabrisjs.com/documentation/latest/api/fs.html)

**Comment by truthSeekr** [comment]
thanks, that can be helpful approach
