### ISSUE TITLE
How I can get the height of a widget which is minimal shrinked?

### ISSUE THREAD

**Issue by sevenuz** [eclipsesource/tabris-js#1554]
The [Layout-Api](https://tabrisjs.com/documentation/latest/layout.html#layout-calculation) describes: if height or top and bottom are not set the widget shrinks to minimal size. How I can get this size? The height property is 0.
Thanks

**Comment by cookieguru** [comment]
You're probably trying to read the height before it has been laid out by the device's layout manager.  Once laid out the it will fire its `resize` event:

```js
const {TextView, ui} = require('tabris');

let label = new TextView({
  centerX: 0, centerY: 0,
  text: 'Hello World!'
}).appendTo(ui.contentView);

label.on('resize', (element) => {
  console.log(element.height);
});
```

See also #1544

**Comment by sevenuz** [comment]
Thx, that worked but the property is not set by his own. I have to set it when the resize-listener is called.
Is this the normal behavior?

**Comment by cookieguru** [comment]
@sevenuz Yes, that is the expected behavior.  When you initialize it, it only exists as a `tabris.TextView` object.  This object is platform agnostic.  It isn't until you append it to the UI that it is actually added to the current layout, and at that point it gets a size.  The `resize` event is triggered when that aforementioned adding to the layout happens.

**Comment by sevenuz** [comment]
Thanks :)
