### ISSUE TITLE
Padding property should be applied inside of scrollable Widgets

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1819]
### Problem description

The `padding` property is applied "outside" of the content of scrollable widgets like `ScrollView` or `CollectionView`.

### Expected behavior

The `padding` should be applied inside scrollable views, to push its content to the inside.

**Comment by patrykmol** [comment]
Fixing this for CV would require adding rows that would mimic padding and adding columns/spacers to edge cells for left/right padding.

As for SV we could squish content view inside of SV instead of squishing whole SV.

In general this is not a quick task to complete, especially due to CV. Currently I do not have a better idea to handle this. Please treat this post as RFC.
cc: @karolszafranski

**Comment by karolszafranski** [comment]
https://github.com/eclipsesource/tabris-ios/commit/45b5fb462ba5718d836e2c864f6896c56558174d
