### ISSUE TITLE
New Carousel Widget

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-js#1846]
### Problem description

I want to be able to scroll some items, just like some jquery plugin does e.g. cycle2,owl carousel,etc.

### Expected behavior

Item can be scrolled horinzontally or vertically with options for autoplay, number of item to scroll, etc.

### Environment

- Tabris.js version: 3.0
- Device: All
- OS: All

### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:
```

**Comment by cookieguru** [comment]
Use a `TabFolder`

**Comment by josiahking** [comment]
@cookieguru how is that possible?
Using tabfolder, you need tabs and tabs need title.
What about settings to autoplay, and number of item to scroll?
How does that work with tabfolder?

**Comment by cookieguru** [comment]
See https://github.com/eclipsesource/tabris-js/issues/1787#issuecomment-460465116

You'd have to implement an autoplay yourself, e.g. using `setTimeout()`.

**Comment by josiahking** [comment]
I see, i will try out that option to see how it fits, but it will be better to have a specific widget just to achieve this.

**Comment by mpost** [comment]
As pointed out, using a `setTimeout` is the right approach for auto playing. It is not overly complex and therefore would not warrant a new `Widget`. Vertical scrolling would be nice too but needs more support from the native clients.

**Comment by tbuschto** [comment]
This is too specialized for a core widget. And as far as i can tell everything that's desired here can be achieved with tabfolder or scrollview or canvas (depending on the desired effect) + timer. I will close this issue for now since there is nothing to do be done for the core framework. If you have further questions on how to achieve certain effects you may still ask here or (better yet) visit our slack channel.
