### ISSUE TITLE
Launching Tabris.js app from the browser breaks it if it is already open

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1915]
### Problem description

When clicking on a link in the browser pointing to a custom URL scheme of a Tabris.js app and the Tabris.js app is already in the foreground, the Tabris.js app will hang up with the screen from the screenshot below. This effectively breaks OAuth workflows.

Works as expected when launching an app, which is not active (had been killed from the app switcher).

Also works as expected when using the `app.launch()` API to launch the app instead of a browser.

![Screenshot_1565017853](https://user-images.githubusercontent.com/2341769/62474797-08b35200-b7a4-11e9-9ffa-ae670712ea48.png)

### Expected behavior

When a Tabris.js app is launched through a browser while beeing in the background, it should be brought to the foreground.

### Environment

- Tabris.js version: tested with 2.8
- OS: API 25

### Code snippet

You can test this by using the example from https://github.com/eclipsesource/tabris-plugin-launchmonitor/tree/master/example and serving a simple `index.html` with [`http-server`](https://www.npmjs.com/package/http-server):

```javascript
<a href="testapp://">Open app</a>
```

**Comment by mpost** [comment]
The problem is that the app consist of two android activities. One is the cordova acitivty which launches the tabris activity. when you open the running app from an url, the cordova activity is brought to the front and overlays the tabris activity.

As a solution you could play around with the launchMode in the cordova activity to use a mode that doesn't bring the app to the front.

Alternatively you could register a third activity that would be the receiver of the testapp:// scheme and would not be in the foreground but launch the tabris activity similar to the cordova activity.

**Comment by mpost** [comment]
@cpetrov please retest in tabris 3.4.

**Comment by cpetrov** [comment]
Works as expected now - without modifying the default activity launch configuration currently consisting of `android:launchMode="singleTop"`.
