### ISSUE TITLE
Code to Open or Navigate to Another Page or Screen withing the tabris app

### ISSUE THREAD

**Issue by Programmeryusuf** [eclipsesource/tabris-js#1946]
### Problem description
How can I open another Activity within my Tabriz App ...I need a code snippet to do that as I don't have any idea on it
or I'd say how to navigate to another Page within the app
Note: I'm using .jsx extension

### Environment

- Tabris.js version: 3.2.0
- Device:  Tecno
- OS:  Android 5.1

### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:
```

**Comment by fax1ty** [comment]
What did you mean by `Activity`? Tabris has a [`NavigationView` ](https://docs.tabris.com/latest/api/NavigationView.html#class-navigationview) that allows you to open different pages and navigate through them. Did you mean that?

**Comment by Programmeryusuf** [comment]
Let me say...to navigate to another page within the app

**Comment by fax1ty** [comment]
**If you want to figure it out on your own, please don't open the `Spoon` section.**
There are many ways to display new content. Starting from the new `Composite` in screen size, ending with hand-made classes based on `Composite`

The easiest way to open new pages, `NavigationView`, about it you can read on the [appropriate page](https://docs.tabris.com/latest/api/NavigationView.html#class-navigationview). And example use you can find [here](https://github.com/eclipsesource/tabris-js/blob/master/snippets/navigationview-page-stacked.jsx):
Also take a look at the documentation page about [`Page`](https://docs.tabris.com/latest/api/Page#class-page)

I wrote a simple version of the usage in TS, you can see it below

<details>
  <summary>Spoon</summary>

You can use `NavigationView` instead of `contentView`, and place page content in new [`Page`](https://docs.tabris.com/latest/api/Page#class-page)s

  ```typescript
let navigationView = new NavigationView({ left: 0, right: 0, top: 0, bottom: 0, toolbarVisible: false })
    .appendTo(contentView);
let examplePage = new Page({ top: 0, bottom: 0, left: 0, right: 0 });
examplePage.onAppear(({target: page})=> {page.append(....)});
navigatorView.append(examplePage);
  ```
  The most recent `Page` that has been append to the `NavigationView` will be displayed.
Don't forget to `.dispose()` previous pages to clear the `contentView` if they are no longer needed
</details>

**Comment by cookieguru** [comment]
There's also a collection of [examples](https://github.com/eclipsesource/tabris-js/tree/master/snippets) all of which are included in the Tabris.js developer app that you can find in the Google Play store and Apple App Store.
