### ISSUE TITLE
Which should i use .js , .jsx , .tsx

### ISSUE THREAD

**Issue by Programmeryusuf** [eclipsesource/tabris-js#1947]
Which Extension is the best for Tabris' apps and the Advantages

**Comment by fax1ty** [comment]
I don't know why, but developers use JSX in all their snippets. Personally I don't like the XML syntax. 
It's hard to say what will be better. That's a pretty personal question. There is only one difference between JS and TS - typings. You will always get hints from the IDE and in case of an error, you do not need to execute the application to detect it.
Personally, I chose TS because it is more convenient to work with, but of course there is no right answer to the question "what language would be better". Here you can draw a parallel between " which is better, English or Vietnamese?"
![image](https://user-images.githubusercontent.com/26363214/66203202-ca111980-e6b8-11e9-9ad6-b9846c24092e.png)

**Comment by fax1ty** [comment]
I think it is better not to open junk off topic issues. If you need help, you can always use the [Slack channel](https://tabrisjs.herokuapp.com/) or If you, like me once a beginner and you have a lot of questions and few answers, I can personally chat with you on Discord (`fax1ty#5512`)

**Comment by Programmeryusuf** [comment]
I'm not on **discord**  sir...can we hook on Facebook or WhatsApp or Twitter sir
@fax1ty

**Comment by Programmeryusuf** [comment]
Tesr

**Comment by fax1ty** [comment]
@Programmeryusuf I have downloaded WhatsApp. So, how I understand, my login is my phone number, +79021543226

**Comment by cookieguru** [comment]
Agreed that [the Tabris.js Slack channel](https://tabrisjs.herokuapp.com/) is the best place for discussions like this; you can find a number of users discussing and asking questions

Also the choice has nothing to do with the framework; it's more of you choice that can be applied to any JavaScript project

**Comment by tbuschto** [comment]
@Programmeryusuf 
Use .js if you want the most simple and least powerful language. It's fine for small projects.
Use .jsx (in addition to .js) if you want XML/HTML-like declerative UI syntax, but don't care too much about type safety.
Use .ts if you are fine with learning TypeScript and want more confidence in the correctness of your code
Use .tsx (in addition to .ts) if you want TypeScript and declerative UI syntax.

We use .jsx in most of our examples since we think it results in the most clean looking code, which is important for showing of the framework, but internally we always use .ts/.tsx.
