### ISSUE TITLE
TabFolder/Tab Pages

### ISSUE THREAD

**Issue by Programmeryusuf** [eclipsesource/tabris-js#1960]
How do I move from a page to another in TabFolder/Tabs like we do in NavigationView

**Comment by cookieguru** [comment]
The [Tabris.js Slack channel](https://tabrisjs.herokuapp.com/) is the best place for questions rather than creating bug reports.

You can use the [`selectionIndex`](http://docs.tabris.com/latest/api/TabFolder.html#selectionindex) property on `TabFolder` to programmatically set the active tab by its integer index, or by the  [`selection`](http://docs.tabris.com/latest/api/TabFolder.html#selection) property to set it directly if you have a reference to the `Tab` object.
