### ISSUE TITLE
Cannot scroll when dragging TextInputs

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#2012]
### Problem description

Scrolling is not possible when pressing on a TextInput widget and dragging. This is critical for the usability of form layouts.

### Environment

- Tabris.js version: 3.3.0, 2.10.0
- OS: iOS

### Related

Possibly related to eclipsesource/tabris-js/issues/1286

### Code snippet

```javascript
import {TextInput, contentView, ScrollView} from 'tabris';

contentView.append(
  <ScrollView stretch>
    {[...Array(50).keys()].map(() =>
      <TextInput stretchX top='prev() 10'/>
    )}
  </ScrollView>
);

```

**Comment by patrykmol** [comment]
This is impossible to fix since once iOS establishes a target that will receive all of the incoming touches (using `hitTest` method) they will all be sent to this specific view. A new target will only be established after current touches have ended (lifting fingers from screen) and new touches begin.

Closing as WONTFIX.
