### ISSUE TITLE
Support custom content in navigation drawer

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#203]
Support modifying the navigation drawer layout to add item group titles and widgets to it.

**Comment by ralfstx** [comment]
Our current idea is to make the navigation drawer available at `tabris.ui.drawer` and to support custom content.

**Comment by ralfstx** [comment]
We agreed that the clients support a new widget type `tabris.Drawer` that represents the navigation drawer. The drawer should support the methods `show` and `hide`. Properties will be added as needed.

The JS side will create a single instance of `tabris.Drawer` and a `Composite` as its only child. This composite should fill the drawer.

**Comment by mpost** [comment]
I would think `open` and `close` is more intuitive as it reflects how you speak about a physical drawer.

**Comment by ralfstx** [comment]
Agreed, the [Android docs](https://developer.android.com/design/patterns/navigation-drawer.html) use the terms open and close. Changed in the description above.

**Comment by ralfstx** [comment]
A new type `Drawer` has been introduced in commit aba577e2. Only when a Drawer is created, the application will have a navigation drawer. The iOS developer app still displays an empty drawer due to a current limitation of the drawer implementation.

Children can be appended to a Drawer just like to any other container widget.

A new type `PageSelector` (commit 08958621) can be used to add top-level pages to the drawer (see [drawer-pages snippet](https://github.com/eclipsesource/tabris-js/tree/master/snippets/drawer-pages)).

**Comment by ralfstx** [comment]
Android implementation still pending

**Comment by paulocarvalhodesign** [comment]
any joy on android implementation?

**Comment by ralfstx** [comment]
The drawer is implemented in the latest Android nightly build.

**Comment by paulocarvalhodesign** [comment]
Awsome :)
