### ISSUE TITLE
Modifying the widget tree in some ways leads to a crash

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#2037]
### Problem description

Modifying a widget tree in a certain way (snippet 1) to achieve the constellation from snippet 2 results into the app hanging up.

Creating the same constellation at once works as expected (snippet 2).

### Environment

- Tabris.js version: 3.4
- OS: Android 9

### Code snippet
Snippet 1:
```javascript
import {contentView, Composite} from 'tabris';

contentView.append(
  <Composite left centerY width={30} height={30} background='red' right='next()' />
)

setTimeout(() => {
  contentView.append(
    <Composite right centerY width={30} height={30} background='blue' />
  );
}, 2000)
```

Snippet 2:
```javascript
import {contentView, Composite} from 'tabris';

contentView.append(
  <$>
    <Composite left centerY width={30} height={30} background='red' right='next()' />
    <Composite right centerY width={30} height={30} background='blue' />
  </$>
)
```

**Comment by mpost** [comment]
After some research it turned out that the code run in the timeout is leading to an endless loop on the js side. This only happens when the width as well as the left and right of the first composite is set. This would be an incorrect layout and width is ignored. setting only left and right lets the snippet work as expected. The same behavior including the endless loop can be observed on ios.

**Comment by mpost** [comment]
to reproduce remove/add the `width` from the first composite: 

```
import {Composite, contentView} from 'tabris';
contentView.append(
  <Composite left right='next()' width={30} centerY height={30} background='red'/>
);
setTimeout(() => {
  contentView.append(
    <Composite right centerY width={30} height={30} background='blue'/>
  );
}, 2000);
```

**Comment by tbuschto** [comment]
This is caused by the connected CLI. The framework is trying to log a warning while in a layout flush, and the remote console feature attempts to send this to the CLI vie websocket, causing another flush. 

It's not entirely unterstood why this doesn not happen all the time, but the propper fix is to let the CLI buffer the messages and send them in a timeout. I opened an issue over there: https://github.com/eclipsesource/tabris-js-cli/issues/80

**Comment by fax1ty** [comment]
I don't know if this is related somehow, but I do similar operations and get the following error: `flush in flush`.
Here is the code that the stacktrace leads to

```ts                        
api.map.list([map.region.southWest, map.region.southWest])
                            .then(data => {
                                let pos = map.positionToScreenPoint(myPos);
                                new MapCrystal({ left: pos[0] / device.scaleFactor - 60 / 2, top: pos[1] / device.scaleFactor - 60 / 2 })
                                    .appendTo(objectsLayer);
                                data.users.forEach(u => {
                                    if (u.nick != player.nick)
                                        new PlayerIcon(true, new Player(false, u.nick, [0, 100], 1, u.emoji, u.guild), { width: 60, height: 60, id: u.nick })
                                            .appendTo(playersLayer)
                                            .moveTo(map, u.pos);
                                });
                                setTimeout(() => loader.close(), 1000);
                            })
                            .catch(err => console.error(err));
```
If I specify the `width` or `height` of `MapCrystal`, everything will work as expected

**Comment by tbuschto** [comment]
@fax1ty Tabris and tabris-cli versions?

**Comment by fax1ty** [comment]
> @fax1ty Tabris and tabris-cli versions?

3.5.0, both
