### ISSUE TITLE
Widgets like TextView sometimes unexpectedly collapse when they should have intrinsic size

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#2038]
### Problem description

In the snippet below, the `TextView` collapses when sized intrinsically, although it should have the size of its content.

![Screenshot_1587665146](https://user-images.githubusercontent.com/2341769/80133674-dcdc3480-859d-11ea-9770-a334d7ce2ad8.png)

### Environment

- Tabris.js version: 3.4

### Code snippet

```javascript
import {contentView, Composite, TextView} from 'tabris';

// When the TextView does not have intrinsic size (e.g. add `right={0}` 
// to the outermost/first Composite), it is laid out as expected.

contentView.append(
  <$>
    <Composite left top height={30}>
      <Composite left={0} top={0} bottom={0} width={30} background='blue'/>
      <TextView left='prev()' top={0} bottom={0} right='next()' text='foo' alignment='centerX' background='red'/>
      <Composite right={0} top={0} bottom={0} width={30} background='blue'/>
    </Composite>
  </$>
)
```

**Comment by mpost** [comment]
After some research it turned out that the code run in the timeout is leading to an endless loop on the js side. This only happens when the width as well as the left and right of the first composite is set. This would be an incorrect layout and width is ignored. setting only left and right lets the snippet work as expected. The same behavior including the endless loop can be observed on ios.

**Comment by tbuschto** [comment]
The code results in a layout that fulfills the defined contraints, @cpetrov. If left and right are defined on a widget its width is defined by the available space, not the intrinsic size. Since the outer composite doesn't have a fixed size it shrinks/grows to a width defined by the minimum space desired by the children. Since TextView doesn't have a "desired" size (explicit or intrinsic) it's ignore in the computation and so no space is left between the two composites.
