### ISSUE TITLE
Tabris application requires permissions that aren't used

### ISSUE THREAD

**Issue by Joshua-Beatty** [eclipsesource/tabris-js#2051]
### Problem description

Simple applications require permissions that they should not.

### Expected behavior

Simple apps that don't use location,  internet, or camera, should not require those permissions. These permissions can scare off privacy minded and security minded costumers, because  with the simplicity of some apps, these permissions seem nefarious. 

### Environment

- Tabris.js version: `3.4.0` and `3.5.0-dev.20200430` 
- Device: N/A
- OS: Android and IOS

### Code snippet
Fork the [Tabris.js Example App](https://github.com/eclipsesource/tabris-js-hello-world)
Build the application using the online build service
Downloaded the .apk 
run ```aapt dumb permissions yourapp.apk``` and notice:
```
package: yourapp.bundleID
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.CAMERA'
uses-permission: name='android.permission.ACCESS_COARSE_LOCATION'
uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
```

**Comment by cookieguru** [comment]
As mentioned in https://github.com/eclipsesource/tabris-js/issues/2043#issuecomment-621197668 this has been fixed already in the nightly builds.  As it is not possible to re-publish code under the same version this is only available in the nightly builds.  It could be available in 3.5.1 if a patch release is made in the future.  In the meantime, you'll want to build your app against that aforementioned version [or later](https://www.npmjs.com/package/tabris)

**Comment by Joshua-Beatty** [comment]
It appears I misunderstood, I thought the fix was that permission strings wouldn’t be required anymore, but the permissions still would be shown. If the permissions were removed then this is closed.

**Comment by Joshua-Beatty** [comment]
Just tested again in `3.5.0-dev.20200430` 
```
./aapt dump permissions app-release-unsigned.apk
package: com.packagenname
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.CAMERA'
uses-permission: name='android.permission.ACCESS_COARSE_LOCATION'
uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
```

**Comment by karolszafranski** [comment]
Regarding iOS:

When you submit an app to Apple, they check which iOS SDKs are referenced in it. That is why your app was rejected and you received an email about missing usage description strings.

An automatic code review cannot infer if that code will be executed or not, it can only check if references exist or not.

That is why even when you build our hello world app it ~is~ was rejected, even though it did not use your location, camera, etc. It was rejected because the Tabris.js framework binary contains references to those APIs. We have camera support in it and so on.

The thing which should keep you calm is that iOS does not allow using any of those APIs without asking the user for permission first. Tabris.js guards you against it, but if you would try to use the camera, location, or any other privacy concerning API (in a pure native app) without asking for permission, the operating system will kill your app immediately.

---

What does it mean for Tabris.js developer?

1. You should not be worried about your application users' privacy because Tabris.js executes only your code. We do not track or log anything in any way.

2. Even if anyone, anyhow would like to "spy" through your application and take pictures or track location, access pictures library, your users are protected by the operating system on their phones.

3. If you plan to use camera or access users' location, please update usage description strings as described in https://github.com/eclipsesource/tabris-js/issues/2043#issuecomment-621197668. 

We have to provide generic descriptions in the platform to make Apple's "automatic code review" happy. Otherwise, every Tabris.js app would need to have them defined in `cordova/config.xml` or we would have to remove all APIs that are based on privacy-sensitive APIs from Tabris.js. Which no one wants, right? :)

**Comment by Joshua-Beatty** [comment]
Ah okay. My bad I understand now. And regarding android, to anyone worried, even though the permissions are technically there in the apk, they are not shown when installing the apk. Thank you for clearing up my misunderstanding.

**Comment by cookieguru** [comment]
@Joshua-Beatty If you are hyper-concerned you can also add a build hook to remove them completely.  [`edit-config`](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#edit-config) doesn't support remove but you can add a [hook](https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/) to scrub them:

config.xml:
```xml
<hook type="before_compile" src="remove_permission.js" />
```

remove_permission.js:
```js
#!/usr/bin/env node
const fs = require('fs');

if(fs.existsSync('platforms/android')) {
	const MANIFEST = 'platforms/android/AndroidManifest.xml';
	let lines = fs.readFileSync(MANIFEST, 'utf8');

	lines = lines.replace(/\s+<uses-permission android:name="android\.permission\.ACCESS_(?:FINE|COARSE)_LOCATION" \/>/g, '');

	fs.writeFileSync(MANIFEST, lines);
}
```
