### ISSUE TITLE
Animations that don't alter opacity break rendering of opacity < 1

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#2060]
### Problem description

When running an animation that does not change the value of opacity, the widget it is run on will be rendered as if it had opacity `1`, although it could have lower opacity.

### Expected behavior

When animating widgets, their set opacity should be retained visually when the animation is executed.

### Environment

- Tabris.js version: 3.5.0
- OS: Android

### Code snippet

```javascript
import {Composite, contentView} from 'tabris';

contentView.append(
  <Composite center opacity={0.4} width={40} height={40} highlightOnTouch background='red'/>
);

setTimeout(async () => {
  const button = contentView.find(Composite).first();
  await button.animate({}, {duration: 100})
  console.log(`Button has opacity ${button.opacity} but it looks as if it had opacity 1.`);
}, 1000);

```

**Comment by mpost** [comment]
This is indeed a bug. It also applies to other properties that can be animated. Eg `transform`.

**Comment by mpost** [comment]
It is actually not a bug for the `transform`. Although one could think that `transform` properties like `translationX` represent their own property the `transform` object is treated as a whole. Meaning if you want to animation one property in the `transform` you will have to specify all other target values of the `transform` properties. Since `opacity` is not part of the transform the android bug still holds true.
