### ISSUE TITLE
Disable/optimize property checks in a productive enviroment

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#210]
This could be achieved simply by exchanging PropertyEncoding.js, either at runtime or during the build.

**Comment by tbuschto** [comment]
I no longer consider this useful in our current infrastructure. To elaborate:  

In our property system we have value conversions (rectifications), value checks, and value encoding. All three tasks are done within one single function, as the check (if one is done) is very often a by-product of the conversion and/or encoding. A separate implementation of the check would be redundant. Therefore, removing the checks in a productive environment would save us little-to-nothing because we still have to do the conversions and encoding. 

In addition, since incorrect values are simply ignored with a warning, removing the check would mean that applications that run fine at development time (aside from a few console warnings) could crash in a productive environment. (I think at the time I made this proposal the checks still caused JS errors.)

**Comment by tbuschto** [comment]
We could consider it for CanvasContext which is used in non-native animations (unlike the widgets that have native animations). However, right now CanvasContext is actually missing a lot of checks, so that would be more relevant when we introduce them.

**Comment by ralfstx** [comment]
There are checks for the number of parameters in CanvasContext. These checks are executed every time a CanvasContext method is called, that is once for every (`lineTo`, `moveTo`, etc.).

I've run the canvas animation demo, both with the checks enabled and with the checks removed, on a Nexus 7 in portrait mode, with FPS counts below 60. In both cases, the performance appeared equal, I couldn't see any difference.

If the checks don't slow down animations, I suppose they won't hurt anywhere else as well.

While removing the property checks at runtime doesn't seem to lead to a performance improvement, it can make applications less robust, because, as Tim stated earlier, JavaScript errors would be escalated to native crashes.
