### ISSUE TITLE
How to use lowdb with tabris.js?

### ISSUE THREAD

**Issue by Nabeel20** [eclipsesource/tabris-js#2121]
### Question
didn't manage to make my own database with fs :(

**Comment by cookieguru** [comment]
Can you share code examples and output?

**Comment by Nabeel20** [comment]
I want - for example - to make a todolist app. Because tabris does not support sync read/write and did not find a lifecycle to add the read file method

**Comment by Nabeel20** [comment]
```javascript
import { contentView, fs, TextView,Composite, Stack, Button, Constraint } from 'tabris';
const path = fs.filesDir + '/db.json'

let db = [{ title: 'Fix database issue', done: false }, { title: 'Ask for help', done: true }];

async function get_data() {
  let tasks_db = await fs.readFile(path, 'utf-8')
  db = JSON.parse(tasks_db)
}

// how to load data then call the function?
contentView.append(
  <$>
    <Stack padding={16} stretchX spacing={10}>
    <TextView text='Your Tasks: ' markupEnabled font="bold 23px" />
      <CustomPage />
    </Stack>
  </$>
);

function CustomPage() {
  let output = [];
  db.forEach(Task => {
    output.push(
        <Composite background='#CAFFFB' padding={10} stretchX >
          <TextView left centerY text={Task.title} font='23px' />
          <TextView left='prev() 10 'centerY right text={Task.done ? 'Done' : 'Not yet'} textColor={Task.done ? '#32BF84' : '#FD4659'} />
        </Composite>
    )
  })
  return output
}
```   @cookieguru  what do you think, please?

**Comment by cookieguru** [comment]
Where do you call `get_data()`?  What is the output or error?

**Comment by Nabeel20** [comment]
When I call ```get_data()```  I got in ```console.log(db)``` all the files, but the UI never changed. Usually when I want to update the UI i call ```$(Widget).only().children().dispose()``` then recall ```$(Widget).only().append(<UI>)``` , Now should I do the same (just got this idea now :smile: ) ?

**Comment by cookieguru** [comment]
As the code is executed the UI is drawn.  If you want your UI to react to changes of variables, you'll need to set up [data binding](https://docs.tabris.com/latest/databinding/).

I would not recommend disposing widgets and recreating them--this is an expensive operation which requires recalculating the layout which is unnecessary for text changes (and most other changes).  It is similar to emptying the `<body>` of an HTML document in order to update the text of one element.

Alternatively, you could reference the widgets in your `get_data()` method and update them programmatically [like this](https://github.com/eclipsesource/tabris-js/blob/master/snippets/button.jsx)

**Comment by Nabeel20** [comment]
Thanks!
