### ISSUE TITLE
Broken hyperlink in TextView

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#2186]
### Problem description

The `&` symbol breaks the hyperlink (`<a href="#">...</a>`) in the markup enabled TextView.

### Expected behavior

Such kinds of symbols should not break hyperlinks in the markup enabled TextViews.

### Environment

- Tabris.js version: 3.8.0-dev.20210526
- Device: iPad 10.2
- OS: iOS 14.6

### Code snippet

```js
const { TextView, contentView } = require('tabris');

new TextView({
  left: 16,
  right: 16,
  centerY: 0,
  text: '<a href="#">Left side & right side</a>',
  alignment: 'centerX',
  markupEnabled: true
}).onTapLink(() => console.log('Tap Link!'))
  .appendTo(contentView);
```

**Comment by cookieguru** [comment]
The `&` alone seems to be valid HTML5; this snippet:
```html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Title</title>
</head>
<body>
<a href="#">Left side & right side</a>
</body>
</html>
```
surprised me because it passes [validation](https://validator.w3.org/#validate_by_input).  Presumably the space makes it not quality for an [ambiguous ampersand](https://html.spec.whatwg.org/multipage/syntax.html#syntax-ambiguous-ampersand).

Should note this snippet renders and works fine on Android.

**Comment by karolszafranski** [comment]
I see that this issue is not specific to anchors. It will not work if you try to make this text bold too.

After having a closer look I see that it's [NSXMLParser](https://developer.apple.com/documentation/foundation/nsxmlparser?language=objc) that fails. We use it to parse HTML and have no insights into its internals.

I suggest using `&amp;` entity to encode the `&` character.

This issue will not be fixed now, because we can't do anything about how the parser works. Replacing `NSXMLParser` with anything else would take a significant amount of work. Please try the suggested workaround.

Thanks @cookieguru for sharing your findings. I'm surprised as well that it passes validation. It seems that only strings with valid entity formats are decoded. For example `&right` also worked, but `&right;` resulted in an error.
