### ISSUE TITLE
Animation with repeat = Infinity always produces "Uncaught promise rejection" after widget disposing

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#2189]
### Problem description

[This](https://github.com/eclipsesource/tabris-js/issues/2140) can help a lot in solving problem.

The problem is that it still continues to execute the animation, even after the object has been destroyed. But we don't have an API for stopping the animation. At the moment, this is an unsolvable problem.

**Workaround:**

```js
widget.animate({ opacity: 0 }, { repeat: Infinity, duration: 1000 })
 .catch(() => { });
```

### Expected behavior

The animation stops after the animated widget is removed
### Environment

- Tabris.js version: any
- Device: any
- OS: any

### Code snippet

```js
widget.animate({ opacity: 0 }, { repeat: Infinity, duration: 1000 })
```

**Comment by mpost** [comment]
Thanks for reporting. We will look into it.

**Comment by tbuschto** [comment]
This is expected behavior: https://docs.tabris.com/latest/widget-basics.html#animations: "If the animation is aborted, e.g. by disposing the widget, the promise is rejected.". Even in the case of the not-yet public `abort` function the promise rejects. That behavior is debatable, but discusion around that should be continued on #2140.
