### ISSUE TITLE
Make device language accessible

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#222]
Currently there is no way of finding out the language used on the device

**Comment by irbull** [comment]
Should we consider using a cordova plugin for this?

**Comment by irbull** [comment]
Related to issue #225

**Comment by jkrause** [comment]
Cordova does not need a plugin,  you simple access ```navigator.language``` of the WebView. We should consider using the same API, but need to supply the information outside of a WebView.

**Comment by hstaudacher** [comment]
We have our own device object to access basic device information. Could we not simply extend it? I mean the information is there.

**Comment by irbull** [comment]
Sure. I guess I'm just trying to understand when we should consider Cordova for system information vs using another mechanism (like the device object). Battery status, device orientation, network signal, location, language, etc... As long as it's obvious how you access these properties.

**Comment by ralfstx** [comment]
I'd also propose that we use the existing `device` object (`tabris.Device` on the clients) because it seems to be trivial to determine the device language, it's static, and we don't need the help of a Cordova plug-in.

This object already has the fields `model`, `platform`, `version`, let's also add `language`. This field should contain a [RFC 4646](http://tools.ietf.org/html/rfc4646) compliant language tag ("en", "en-US", "de-DE", etc.) On this basis, we could also consider to copy it to `navigator.language` for Web compatibility. However, I don't think that those "Web objects" like navigator should be our primary API.

**Comment by hstaudacher** [comment]
I'm not sure if we need a separate issue for this, but can we add the device time/timezone at the same time? I think it has the same category ;)

**Comment by hstaudacher** [comment]
Just to explain my thought: On the server the device object (ClientDevice) extends RAPs ClientInfo. Timezone and language are available on ClientInfo. So, I think it's ok to have those information available on the device object in tabris.js.

**Comment by ralfstx** [comment]
I think there are some open questions related to timezone:

* ClientDevice only provides the timezone *offset*, because that's all we can get from the browser client. Can we access the timezone itself on the mobile clients?
* When you're travelling, the timezone can change. Is a static field still sufficient?
* The timezone information should be consistent with what is returned from `new Date().getTimezoneOffset()`. How could we achieve this?

Therefore I think we should have a separate issue to discuss these questions.
