### ISSUE TITLE
Provide API to invoke a SearchAction

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#239]
A `SearchAction` can be invoked programmatically by issuing a `call` to the method `open`.

Options:
- a new method `action.open()`
- an event that triggers the call internally, e.g. `action.trigger("open")`

**Comment by jkrause** [comment]
Is the ```SearchAction``` really an Action or is it rather a specialized ```Page```? It behaves differently than an action, because it does not only trigger an event, but also shows a specialized UI. And the "open" method also indicates a page, not an action.
It is clearly not a normal page, because on Tablets under iOS it is more like a dialog.

Can normal actions be invoked by triggering a "selection" event on them?

**Comment by ralfstx** [comment]
I see it as an Action with a default behavior. A `Page` is a part of the application's navigation and a UI container. This is not the case for a `SearchAction`. Technically, `SearchAction` is a specialization of `Action` both on the native clients and on the JS side. I think it should also fire a `selection` event, if it does not, that's unexpected.

Thinking about it, the SearchAction is a composition of two rather unrelated things. It may be clearer to decouple the search ui from the Action. You'd create a normal Action and open the search ui in a `selection` listener. This would allow to open the search UI programmatically without any additional API.

Actually, it's currently not a `selection` event that opens the search ui, but an `open` call. This method is only supported on SearchAction, not on Action.
