### ISSUE TITLE
Support font variants

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#24]
Support selecting from different variants (weight, style, etc.) of a font family.

**Comment by tbuschto** [comment]
Some clarification: In constrast to what we have right now this change would add more detailed weight (currently we have bold or not bold) and more font families.

**Comment by cpetrov** [comment]
+1

**Comment by tbuschto** [comment]
Okay, I wanted to start implementing font for windows and would like to use the newer syntax (https://github.com/eclipsesource/tabris-js/issues/24#issuecomment-59015335) right away. The js code would have to be changed to give the clients the font as an object, so android and ios would have to support both format for a period of transition. 

However, this would also require a change in API behavior: Currently getting the font property without ever setting it returns the widgets default font. (When font was set by application code the value is cached, so the native getter is not called.) We would change that behavior so that the value "initial" is returned instead. That way the native getter would never be called and only the cache would be used. The native getter on both platforms would not be changed (return array) to allow backwards compatibility (for a while). 

Question is if that change is still in line with our API documentation, as it states " The value "initial" resets the font to its (platform-dependent) default.", but not whether a get then returns the default or "initial".

**Comment by ralfstx** [comment]
I'd like to move forward with the change suggested in #24 (which involves using a font object instead of an array on the nativebridge).

Not sure if getting the font of a widget is a real use case. If not, +1.

We can change the documentation to state that "initial" *represents* the platform default. I wouldn't consider this as a regression.

**Comment by mpost** [comment]
@tbuschto the proposed change is fine with me. We should come up with a more robust way to get the default font details anyways.
