### ISSUE TITLE
Provide API to modify z-order

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#249]
Currently the z-order is defined by the order in which widgets are added to their parent. When a specific z-order is required, manipulating the creation order results in hardly understandable code (see #242).

**Comment by mpost** [comment]
Android supports the concept of elevation as described in https://developer.android.com/training/material/shadows-clipping.html

When we decide to add specific api to it we should add support for 
* <code>elevation</code>
* <code>translationZ</code>

**Comment by mpost** [comment]
Closing since it is implemented in the Tabris.js 1.5 release.

**Comment by cpetrov** [comment]
I think this issue was closed by mistake, because the Android-specific `elevation` property is independent from the order the widgets are drawn in.

On Android, [drawing order](https://developer.android.com/reference/android/view/View.html#Drawing) is the order the widgets are drawn in and is defined by the location of nodes in the widget tree. This corresponds to the term `z-order` used in this issue. 

[Elevation](https://developer.android.com/training/material/shadows-clipping.html) is a concept which allows modifying the appearance of a widget's shadow and overriding the drawing order. It's purpose is more semantic, i.e. to emphasize on an importance of an UI element than to simply draw it behind or before other elements.

**Comment by mpost** [comment]
The z-order will be fixed in https://github.com/eclipsesource/tabris-js/issues/1224.
