### ISSUE TITLE
CollectionView should support appending items when reaching the end of current item list

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#272]
https://github.com/eclipsesource/tabris-js/issues/271

**Comment by ralfstx** [comment]
Items can be appended to a CollectionView using the `insert()` method. The reload can be triggered from the `itemchange` event when the last item is resolved. This works well, but since this event is fired on the cell, it feels like the wrong hook. Moreover, items being resolved and items become visible are semantically different things.

We may think about an additional event like `itemappear` on CollectionView itself.

**Comment by mpost** [comment]
I also vote for a "scroll position" listener.

**Comment by ralfstx** [comment]
Here's a code example for Android: https://gist.github.com/ssinss/e06f12ef66c51252563e

**Comment by mpost** [comment]
Since we have all the low level infrastructure in place (eg item visible listeners) to create some more advanced JavaScript based abstraction on top of it i'll close the issue.
