### ISSUE TITLE
Support Cordova events

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#285]
Cordova supports a [number of events](https://cordova.apache.org/docs/en/4.0.0/cordova_events_events.md.html
) such as `deviceready`, `pause`, `resume`, `backbutton`, and others. These events are currently not fired in Tabris.js.

**Comment by mpost** [comment]
I think for us the most important parts are the pause, resume and backbutton (for android)

**Comment by hstaudacher** [comment]
The most straight forward approach to implement this would be to add the event firing to the Cordova integration on the native side. 

Anyway, I'm not sure if it's a good idea to rely on Cordova for those core events. I think it would be optimal if tabris.js would support a counterpart. This would also allow to map the event to the cordova events on the js side of the cordova integration.

**Comment by tbuschto** [comment]
Okay, so as I understand it these are cordova-core feature that can not be supported in any generic way like cordova plug-ins are. We would have to built explicit support for them, and since we already have most of these events supported via the internal tabris.app service API, we can just use that.

But if we do so, I would suggest to also expose tabris.app feature via a tabris.js-like API, and then build the cordova support on top of that API. It's only a tiny amount of additional code, but in return we have non-alien looking, cordova-independent API for that stuff.

Here is a demo of the features of tabris.app working in tabris.js:

    tabris.registerType("_App", {
      _type: "tabris.App",
      _listen: {Open: true, Pause: true, Resume: true, Inactive: true, BackNavigation: true},
      _properties: {badgeNumber: true, screenProtection: true}
    });
    
    ["Open", "Pause", "Resume", "Inactive", "BackNavigation"].forEach(function(type) {
      tabris("_App").on(type, function(ev) {console.log(type, JSON.stringify(ev));});
    });
    
    tabris("_App").set("badgeNumber", 23);
    tabris("_App").call("startInactivityTimer", {inactivityTime: 1000});

I would suggest to either use the tabris object directly (and use it for the orientation event as well), or to introduce a tabris.app object.

**Comment by hstaudacher** [comment]
+1 for `tabris.app`. They are really app specific app events/properties. I also thought about device but this does not fit well.

Regarding the orientation I'm not sure. I think they are thrown when the physical device rotates and not the App. So `tabris.app` may not a good home for orientation.

**Comment by mpost** [comment]
I also vote to support app events natively in tabris.js. Pause and Resume are very often used to eg. persist data etc. Therefore we should offer it and don't force cordova upon people.

**Comment by ralfstx** [comment]
The `tabris.app` object has been introduced in e57674e05fe6bb26f689756fc7f4c4257302cd14. Documentation is in [app.md](/eclipsesource/tabris-js/blob/master/doc/app.md).

**Comment by hstaudacher** [comment]
we still need to map the cordova events to the app events.

**Comment by tbuschto** [comment]
Added this feature to the cordovas platform.js, but I can't test it right now. It should work on monday though.

**Comment by mpost** [comment]
Since we already implemented `pause`, `resume` and the `backnavigation` event on the tabris.js `App` object i will close this issue.
