### ISSUE TITLE
"Show Confirm Dialog" option does not work in Cordova example of dialogs

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#309]
When selecting the "Show Confirm Dialog" button in the Cordova example of dialogs, nothing happens.

This bug affects iOS and Android.

**Comment by calebeaires** [comment]
Same here. 
tabris-js 0.9.2

**Comment by jordiboehmelopez** [comment]
The problem stems from the JS implementation of that plugin (notification.js).
There is one section where the platform is checked. Usually it would be `ios` or `android`, but in our case its `tabris-js` which leads to a different code path. This different (and not desired) code path leads to an result where the two button strings are converted into a comma-separated string instead of an array with string (which is expected by the native implementation).

I think we have two options to solve this specific problem:
a) The code of the plugins needs to change and take `tabris-js` into account
b) Our cordova platform ist identify itself as `ios` or `android`

**Comment by jordiboehmelopez** [comment]
...  and I think option "b" is not an option ;)

**Comment by jordiboehmelopez** [comment]
The bug is already reported will be fixed in our tabris-js-cordova repository

**Comment by hstaudacher** [comment]
Already fixed. Will be included in 0.9.3
