### ISSUE TITLE
Warning messages about incomplete layout data "enforces" boilerplate code

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#434]
The warning about missing layout data is often times annoying since it is possible and comfortable to simply rely on the default values of left: 0 and top: 0. Thereby less boilerplate typing is required.

**Comment by wilsonna** [comment]
Hi all, it may be a bit late for me to comment since the status is already at "ready", but I would like to make a couple of suggestions relating to the layoutData defaults which perhaps could be introduced in later versions since they are probably non-trivial.

Instead of defaulting to top:0, left:0, I think defaulting to top:this.parent().children().last().top(), left:this.parent().children().last() would be more intuitive. The syntax is all made up, but I think you know what I'm getting at.

Alternatively, introduce a "wrap" property for the Composite widget which allows all it's children to simply appended after the last widget according to the sequence they were added, and wrap to the next "line" if it exceeds the screen width.

We can also do away with the warnings for missing horizontal / vertical definitions for layoutData if the defaults in (1) are in place.

**Comment by ralfstx** [comment]
@wilsonna You're requesting a *row layout*. That's an interesting option, but if we made it the default, we had to decide whether it should be horizontal or vertical. If horizontal, the `left` property would point to the previous widget and `top` would be `0`. For vertical, it would be the other way `round. I'm not sure it this makes a good default.

However, we are aware that grid and row layouts are needed and we're planning to provide those.

**Comment by wilsonna** [comment]
@ralfstx Thanks!

**Comment by ralfstx** [comment]
It would probably be more of a *fallback* than a default, as these values would be overridden by setting other parts of the layoutData (e.g. setting `right` would kill the `left: 0` fallback).

* When none of `left`, `right`, `centerX` is set, the horizontal orientation falls back to `left: 0`.
* When none of `top`, `bottom`, `centerY`, `baseline` is set, the vertical orientation falls back to `top: 0`.

Example:

value | effective
---|---
`{}` | `{top: 0, left: 0}`
`{top: 10}` | `{top: 10, left: 0}`
`{top: 10, right: 10}` | `{top: 10, right: 10}`

I suppose that empty layoutData should be handled just like no layoutData, so setting `layoutData: {}` should have the same effect as not setting them at all, right?

**Comment by mpost** [comment]
I am very much in favor of the table above.

**Comment by ralfstx** [comment]
Since the behavior should be the same when no layoutData is provided at all, these fallbacks have to be implemented on the clients.

**Comment by ralfstx** [comment]
Fallbacks are implemented on the clients, warnings removed as of 1aa3fa7281312b932410c893a81c529a60b38959.
