### ISSUE TITLE
Support Playing audio media

### ISSUE THREAD

**Issue by ruarch** [eclipsesource/tabris-js#459]
How do I play mp3 and other audio extensions files and streams?

**Comment by hstaudacher** [comment]
Maybe one of these will work: http://plugins.cordova.io/#/search?search=audio

**Comment by ruarch** [comment]
Hi...Will appreciate it if u can recommend one...I tried the video control to stream a radio url it worked...I will like to have my own custom controls for the video control.

**Comment by ruarch** [comment]
http://docs.phonegap.com/en/edge/cordova_media_media.md.html does not seem to work

**Comment by maxapps** [comment]
Did you ever figure out how to do this? I have the same requirement and have just started researching possible solutions. Any help you can provide would be appreciated.

**Comment by cookieguru** [comment]
[cordova-plugin-nativeaudio](http://github.com/floatinghotpot/cordova-plugin-nativeaudio) works but doesn't support URLs or streams.

**Comment by cookieguru** [comment]
[apache/cordova-plugin-media](cordova-plugin-media) works great!  Currently listening to this Icecast-powered MP3 stream:

```js
var media = new Media('http://knhc.streamguys1.com/live', function() {
	media.play();
});
```

Then you can build controls using Tabris.js (like a play button, etc) and just call `media.play()` when the particular control is tapped.

Only downside I see so far is that the app asks for recording permission on Android since the plugin supports recording.  I've only done a debug build on Android so far, will have to see if this carries through on the release build.  Of course this isn't a show stopper but based on reviews in the Play Store (and the changelogs that address them) some users freak out when they see permissions that they deem unnecessary--especially phone and microphone.

**Comment by mpost** [comment]
@cookieguru great to hear that the plugin works as expected. :) Have you tried it on iOS as well?

I'll close the issue for now.

**Comment by cookieguru** [comment]
@mpost Not yet, but I'm planning on doing so this weekend

**Comment by cookieguru** [comment]
Haven't been able to resolve iOS key signing issues to test this out myself, but I would say that the cordova-media-plugin works on iOS since it was added in eed37ea21642ddb3fc07b7a2812a9a82cbabf679.

For the recording permission on Android, the easy solution is to fork the plugin and remove the permission; the steps are outlined [here](http://stackoverflow.com/a/25062877/1810770)

**Comment by mpost** [comment]
@cookieguru Yeah the audio recording permissions that are required is most unfortunate. Simply removing the permissions could result in problems with plugin. Have you tried to run it when the permissions are removed?

**Comment by ifurnadjiev** [comment]
We still have some problems with local (embed) media file playback on iOS - the path to the file can't be resolved. We will investigate the issue.

**Comment by cookieguru** [comment]
@mpost is there another way to add plugins without having to publish them on npm?  It'd be great if I could add them via a git URL.

**Comment by mpost** [comment]
You can include plugins by git repo as eg shown here: https://github.com/eclipsesource/tabris-calendar

That applies to all cordova plugins.

**Comment by cookieguru** [comment]
Happy to report that this plugin works fine on Android by simply removing `<uses-permission android:name="android.permission.RECORD_AUDIO" />` from `plugin.xml`.

The following methods worked as expected:
- `getCurrentPosition`
- `getDuration`
- `play`
- `pause`
- `release`
- `seekTo`
- `setVolume`
- `stop`


- `startRecord` Will call the error callback registered when initializing `Media`.  While the docs indicate this will be an object, it instead returned the string "setAudioSource failed." (referring to the native Android function [MediaRecorder.setAudioSource](http://developer.android.com/reference/android/media/MediaRecorder.html#setAudioSource%28int%29))
- `stopRecord` - Not tested
