### ISSUE TITLE
Concept: Declarative UI

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#500]
Tabris.js should support a way to define a user interface in markup. It should also be possible to combine Tabris.js with frameworks that provide databinding in combination with declarative UI.

**Comment by irbull** [comment]
This particular issue is just a concept, but it would be nice to determine how we will support declarative UI. Will embed JS in a markup (like HTML) or embed markup in JS (like Angular). Is HTML style markup the best choice, or are there other approaches such as markdown? Finally, are there existing tools / technologies we should 'simply' use here.

**Comment by ralfstx** [comment]
> Is HTML style markup the best choice, or are there other approaches such as markdown?

XML dialects are used everywhere for declarative UI: Angular, React, NativeScript, Android, Vaadin, Gnome, Qt, XUL, XAML, etc. XML seems like the natural choice for declaring UIs. It's well suited for nested structures and the distinction of elements and attributes map nicely to widgets and properties.

> Will embed JS in a markup (like HTML) or embed markup in JS (like Angular).

With the backticks in ES6, embedding markup in JS becomes really feasible. However, since embedding one language in another mostly comes at the price of poor editor support, I think this should only be done for snippets (e.g. cell templates), not for entire UIs.

In a first version I think we could simply support XML files and refer to them from JS. This seems pretty straight forward.

For me some open questions are:

- how and when is the XML parsed?
- who instantiates a UI (framework or application code)?
- will we support templates in the future, and if so which template engine to use - will this affect how we process XML?
- how to include dynamic content such as cell templates for CollectionView, how does our approach relate to established technologies ...

**Comment by ralfstx** [comment]
I've looked into several frameworks and has discussions with @tbuschto, @jkrause, and @mpost. A summary of the topics considered and draft code examples can be found in [tabris-concepts](https://github.com/eclipsesource/tabris-concepts/tree/master/declarative-ui), a new git repo I've created to keep those drafts, PoC, etc.

We came to the conclusion that Declarative UI would only result in an improved programming model if it supports data binding and a somewhat simplified layout definition. We'd suggest to address both topics before we implement Declarative UI.

I've opened #544 for Declarative UI and #545 that suggests an improvement to layoutData.

**Comment by wilsonna** [comment]
Although this may not be implemented anytime soon, I would like to throw in an idea for consideration.

Allow reusing of Composites by means of custom tags which also supports data binding. e.g.

Custom Tag Definition:
    &lt;Composite tagId="MyCustomComposite" ....>
    &nbsp;&nbsp;&nbsp;&nbsp;&lt;TextInput text="{{this.title}}"..../>
    &nbsp;&nbsp;&nbsp;&nbsp;&lt;ImageView ..../>
    &nbsp;&nbsp;&nbsp;&nbsp;......
    &lt;/Composite>

Usage (data binding to "book" model):
    &lt;Composite ....>
    &nbsp;&nbsp;&nbsp;&nbsp;&lt;MyCustomComposite title="{{book.title}}"/>
    &lt;/Composite>

**Comment by ralfstx** [comment]
@wilsonna Yes, re-usable widget components (in the style of web components) are on [the list](https://github.com/eclipsesource/tabris-concepts/blob/master/declarative-ui/concept.md#reusable-components).

BTW, I've edited your comment for readability. You can use [fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) for XML :wink:

**Comment by wilsonna** [comment]
great, thanks! :smile:
