### ISSUE TITLE
Concept: Custom widgets and PoC for Switch Widget

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#501]
Define API and packaging for custom widgets:
 - should use (an extended) cordova plugin mechanism
 - should use Swift for iOS

**Comment by irbull** [comment]
A few other notes:
 - how do we use 3rd party libraries.

**Comment by irbull** [comment]
There are three parts to this work:
 1. A JS API for registering new widgets. This is required because JS doesn't just pass all properties / widget types through. It validates them first.
 2. Android / iOS API for creating the widgets.
  - This will also require helpers for using existing properties. For example, clients should not have to handle properties such as setBounds. But they should be able to overwrite how existing properties are handled if they choose.
 3. Build infrastructure. This includes *how* they will contribute the widget, as well as how to bundle the APK / IPA with this extensions. Use of 3rd party libraries (iOS and Android) will also need to be supported.

**Comment by irbull** [comment]
I've managed to create and install a cordova plugin that can reach into our native API on Android.

**Comment by hstaudacher** [comment]
We also have a working PDF widget for iOS

**Comment by irbull** [comment]
And is this a proper Tabris widget with properties, layout, listeners, events, styles, etc..? If so, why are we doing a PoC if we already have a PoC?

**Comment by mpost** [comment]
We also have the same pdf widget for android which should also work as a bundled cordova plugin. The missing part is the registration of the plugin in tabris-android but that could be done in the onCreate or onStart of the plugin i'd think.

The missing part for me is proper API for a plugin to be developed against. At the moment everything is internal but some functionality needs to be exposed to the public to make life as a plugin developer easier.

**Comment by mpost** [comment]
Btw... holger is referring to a cordova plugin for tabris-remote

**Comment by irbull** [comment]
I now have a working SwitchWidget with Tabris.js 1.0 (without any code changes to TabrisAndroid). The entire contribution is done via a Cordova plugin with the definition of the widget done in JS using TabrisJS internal API. While I have some basic listener support (I can get selection events) I can't seem to get checked / unchecked events. The problem is I don't understand how to read this:
```
    select: {
      name: "Selection",
      listen: function(state) {
        this._nativeListen("Selection", state);
      },
      trigger: function(event) {
        this.trigger("select", this, event);
      }
    },
```
I'll take a look again with fresh eyes, and if I'm still having problems, I'll contact @ralfstx or @tbuschto.

The good news is that PoC is now working for Android and with another day of work I should be able to carve out the tasks we'll need to do to make this real. I'm using the Android API as is, but I think we will need to provide a better API for users. @mpost will likely have some good ideas here.

**Comment by irbull** [comment]
I have a working example of the switch widget working on Android. I'm just finishing a report on what tasks need to be done to make this real. This closes this 'concept issues.
