### ISSUE TITLE
Using additional Cordova plugins without building the app

### ISSUE THREAD

**Issue by ruarch** [eclipsesource/tabris-js#514]
Can I use plugins like org.apache.cordova.geolocation in the tabris app, without building the app first?

**Comment by mpost** [comment]
Since the `org.apache.cordova.geolocation` plugin is not part of the Tabris.js app from the app stores, you would need to create your own cordova build to support geolocation. You can find out what plugins are bundled within the Tabris.js app on the plugin page inside the app.

Luckily the process to create your own build is rather simple: https://tabrisjs.com/documentation/1.0/build#build-service

One note on the geoloaction plugin. The plugin `org.apache.cordova.geolocation` does not add native support for Android. In fact it has no code for Android what so ever since the Android WebView already provided support for geolocation natively so there was no need for the cordova plugin to add any native code.

We are aware of that shortcoming and looking into how we can remedy that problem. In the meantime you should look for another geolocation plugin that adds native Android bits as well.

**Comment by wilsonna** [comment]
This is the only one which I found to work https://github.com/Moussawi7/Cordova-GPSLocator , although it's a little basic.

**Comment by capotti** [comment]
Understanding cordova plugin integration:

I successfully embedded barcodereader - because it's part of the tabris app.
But Emulator gives error: undefined is not an object (evaluating cordova.plugins.barcodeScanner)

Another plugin (installed via cordova cli) errors with
undefined is not an object (evaluating window.tabrisJsPlugins.cards)
But code corresponds to https://github.com/jokorivai/cordova-plugin-tabrisjs-card#3-installation


I have skipped a necessary step?
When use "cordova.plugins" and when use "window.tabrisJsPlugins" ?

**Comment by cookieguru** [comment]
The Tabris.js Developer App that you find in the app stores has a few Cordova plugins already installed so you can test out functionality.
When you build your own app, you need to add any plugins that you want to use.  Since these plugins access native functionality, they must be added when the app is compiled*.  In short, if you haven't compiled the app to a binary, you won't have any of the plugins.  Running `cordova plugin add` only adds the entry to the `cordova/config.xml` but doesn't modify the binaries.  To do so, you must build you app, either with the [Tabris.js cloud build service](https://tabrisjs.com/documentation/latest/build) or by [building locally](https://tabrisjs.com/documentation/latest/local-build).

You can build your app as a Debug version, which will retain the development options seen in the Tabris.js developer app, allowing you to reload code from your development machine via HTTP.  Once you have finished your development, you'll generate signing keys and build a release version that will contain all your plugins and source code but none of the development features.

>  When use "cordova.plugins" and when use "window.tabrisJsPlugins" ?

Never, follow the instructions from the plugin's documentation; in this case you'll always access it via `cordova.plugins.barcodeScanner`.


*The plugins aren't included in your own build because not every app will need the functionality of the plugins.  For example, if you're building a business calculator, you won't need any of the barcode scanning capabilities, so it's not added because doing so would make the app depend on the camera permission.

**Comment by capotti** [comment]
---
lost entry:
---

I have successfully embedded phonegap-plugin-barcodescanner - because it's part of the tabris app.
But ioS emulator shows me the error:
`undefined is not an object (evaluating cordova.plugins.barcodeScanner)`

Another plugin (installed via cordova cli) errors with
`undefined is not an object (evaluating window.tabrisJsPlugins.cards)`
But code corresponds to https://github.com/jokorivai/cordova-plugin-tabrisjs-card#3-installation
`var createCard = window.tabrisJsPlugins.cards.createCard;`

I have skipped a necessary step?
And I wonder when use "cordova.plugins" and when "window.tabrisJsPlugins" ?

**Comment by capotti** [comment]
> cordova plugin add only adds the entry to the cordova/config.xml but doesn't modify the binaries

`cordova plugin add` also create new folders in "mytabrisapp/cordova/plugins"
After tabris manual build process `tabris build ios` I found new folders within "mytabrisapp/build/cordova/plugin". Aren't these folders my "binaries"?

After restart of the emulator I was successful. Maybe a cache problem...
Tank you!!

A little improvement suggestion:
https://www.npmjs.com/package/cordova-plugin-tabrisjs-card#creating-a-card
shows example:
`var card1 = createCard('Card1 Content', 'Card1 Title').appendTo(page);`
This does result in error "options.cornerradius is undefined".
You may change documentation
or set options to {} by default (around line 59 in tabriscard.js)

**Comment by cookieguru** [comment]
> Aren't these folders my "binaries"?

By binary I was referring to the `apk` or `ipa` file that the build generates.  I haven't used the local build so I can't comment on that.

The `cordova-plugin-tabrisjs-card plugin` was created by a third-party developer and @jokorivai han't fixed that issue: https://github.com/eclipsesource/tabris-js/issues/1139#issuecomment-280093148

**Comment by capotti** [comment]
Ok, tried with phonegap plugin "istablet"
`<plugin name="uk.co.workingedge.phonegap.plugin.istablet" spec="~1.2.0" />`
How to access the window.isTablet property, set by the plugin?

```
cordova.plugins.isTablet
cordova.plugins.window.isTablet
```
??
Seems not to work (undefined)

**Comment by mpost** [comment]
@capotti I can't comment on the isTablet plugin but if you should not rely on these kind of plugins but rather adapt your ui based on the size of the screen. Eg. use the `resize` callback on the `tabris.ui.contentView` to get the current available screen space and build your ui accordingly.

**Comment by capotti** [comment]
Youre right!
Because sreen object returns "dip" this solution sufficient:
```
var isTablet = false;
if (screen.width >= 768 && screen.height >= 768) isTablet = true; 
```

**Comment by cookieguru** [comment]
768 is not a good number to test against.  Many phones on [this list](http://dpi.lv/) would return true.

**Comment by capotti** [comment]
You're sure?
This is a common way to identify device width Media Queries in CSS.
My experience is:
The **width** of a phone in Device Indipendet Pixels (**dip**) never reaches 768 Pixels.
So if width and heiht of the screen is > 768 its an tablet.

**Comment by jokorivai** [comment]
@capotti @mpost @cookieguru Thanks for the input.

according to 
```undefined is not an object (evaluating window.tabrisJsPlugins.cards)``` I can't comment on this.
But for default parameter value, i.e. `options = {}`, I just fixed it.

**Comment by mpost** [comment]
@capotti The meaning of the word "tablet" is very blurry with so many different device sizes. I would rather start to think in buckets that a device falls into. eg. large/medium/small etc.

**Comment by capotti** [comment]
To think in buckets is a good way. Agreed.

But nevertheless common breakpoints only works, because manufacturers keep implied conventions:

768 dip is tablet portrait
1024 dip is tablet landscape

bootstrap.js 3 breakpoints:
< 768, < 992, < 1024, < 1200, >= 1200
bootstrap.js 4 breakpoints:
< 576, < 768 < 992 < 1200, >= 1200
