### ISSUE TITLE
Define Native & JS API and packaging for custom widgets

### ISSUE THREAD

**Issue by irbull** [eclipsesource/tabris-js#517]

**Comment by jkrause** [comment]
We should define the minimal API that is necessary to implement a custom widget which is part of our widget tree. The API will be provisional for now and may change at any time. Custom widgets are packaaged as Cordova plugins.

iOS already defines a set of public header files that have been used successfully to implement custom widgets.  Those headers can serve as a starting point.

**Comment by ralfstx** [comment]
For all platforms, we need to

- Implement some kind of hook to **register custom widgets**. Consumers of a custom widget should only need to include the widget, not add any build hooks or write application code to register the custom widget.
- Agree on a minimal **subset of interfaces**, extract and publish them.
- Provide some **documentation** on how to write a custom widget.

For iOS, we should also ensure that the interfaces are Swift compatible (eclipsesource/tabris-ios#761).

**Comment by gosia-eclipsesource** [comment]
As @jonek commented in issue #469, it would be nice to use the CardView widget as an example of a custom widget.

**Comment by mpost** [comment]
We have developed a solution on how to register custom widgets inside the native infrastructure on Android. We use the AndroidManifest.xml supporsts a <code>meta-data</code> entry. In this entry we let the plugin developer provide a fully qualified name to its <code>IOperator</code> (the class that handles protocol messages.

The following snippets shows how a <code>meta-data</code> can be added from the plugin.xml file of a cordova plugin without requiring any intervention from the consumer of the plugin:

```xml
<config-file target="AndroidManifest.xml" parent="/manifest/application">
  <meta-data
    android:name="com.eclipsesource.tabris.android.OPERATOR.com.domain.app.myplugin"
    android:value="com.domain.app.MyPluginOperator" />
</config-file>
```

Since each <code>meta-data name</code> has to be unique in the manifest we have to prefix the name with <code>com.eclipsesource.tabris.android.OPERATOR</code> followed by a plugin specific identifier. We highly recommend to use a fully qualified name as show above.

**Comment by tbuschto** [comment]
We already did some API improvents on the JS, and pretty much worked out how the final API should looke like. Here is what still missing:
* Instead of prefixing special configurion parameters in registerType with "_", extract the non-configuration parameters (which will be put on the prototype) into a "members" object parameter.
* Revise the property "type" syntax to replace the current array notation with strings.
* Instead of giving an object with set/get functions, let "access" consume string similar to "type". Examples would be "cached", "uncached", "cached readonly", "cached static", etc.
* Automatically give the wiget as the first parameter to event listener so that there is no need to implement custom trigger functions.
* Optional: Combine the property type configuration keys into a single string that can be given instead of the object, e.g. "cached int 5".
