### ISSUE TITLE
Remote debugging with Eclipse - port 20001 is closed

### ISSUE THREAD

**Issue by sand123** [eclipsesource/tabris-js#561]
Hi! I'm trying to connect Eclipse for remote debugging.
Should I use Google Play developer app or my custom build app (with online service) with `debug=true` is enough? Code (tabris.js 1.1.0) is loaded via local http url and running on android 5.1, I don't have any firewalls on device, port 20001 is closed - all done as in your blog [eclipsesource.com/blogs/2015/04/17/debugging-tabris-js/](http://eclipsesource.com/blogs/2015/04/17/debugging-tabris-js/)

**Comment by mpost** [comment]
You should be able to use the app from the store or your own custom build when you have <code>debug=true</code> (as you described above). Therefore everything should work as expected.

If you can't bring it to work we will look into the issue further.

**Comment by davehibshman** [comment]
I too followed the article referenced here:  eclipsesource.com/blogs/2015/04/17/debugging-tabris-js/, and I also cannot connect to port 20001 on my device's (Samsung Galaxy S5 - Android 5.0)  IP address.  I start the app from "My Scripts" in the developer app, which I added via a URL pointing to my local Linux box running a node http-server in the app dir.  App runs and works fine.  When I try to connect via Eclipse to port 20001 and I get "connection refused error".  I am also not running any firewalls that I know of.  Previous poster referenced a "debug = true" setting somewhere - I don't see any reference to setting this in the article.

The article also doesn't make it clear if I must actually build an app and be running it via the generated APK in order to debug or I can just run from the developer app and debug.  The scratchpad is referenced in the article and then sample app code is provided, but it doesn't note whether you need to build it or can just run it from My Script after pinning in scratchpad.  No mention of running from My Scripts added via URL or from My apps for that matter.  Comments are closed on the article.  

Maybe it's just supposed to work and isn't for me.  Any clarification you can provide would be much appreciated.  Meanwhile, I'll try uploading to GitHub and building and see if that helps at all.

**Comment by davehibshman** [comment]
Interestingly, upgrading Eclipse to Mars version (latest) it is now working!

**Comment by davehibshman** [comment]
Another update in case it helps anyone.

* Samsung Galaxy S5, Android 5.0, Tabris Dev App 1.3.0 (just updated today)
* I linked an app deployed to my web server accessible via the Internet on the My Apps page.
* I am having trouble getting over-the-air debugging working reliably.

After running a port monitor app on my device I am able to see port 20001 becomes open the first time I start my app, but then closes within 3 seconds.  Afterward any immediate attempts to reload from dev console, exit out of my app, or even exit the Dev App and then come back in and run my app the port stays closed - doesn't show open again.  After waiting 10 to 15 minutes and exiting the Tabris Dev App, coming back in, and then starting my app again I see this same behavior - open for a few seconds, then closed, any immediate restarts stays closed.

If I carefully time starting my Eclipse StandAlone V8 Debug profile in the 3 second window after the first time I start my app, then I am able to connect reliably and the port seems to stay open so I can debug, though it is fairly slow.  If for some reason I need to restart, I have to wait 10 or 15 minutes and try again, and follow the same process and it seems to work.

I suspect something on my phone is causing the port to be closed and held onto for a while. For now I can get it to work, though patience is required.

**Comment by peterzen** [comment]
Thanks for sharing this @davehibshman – I'm seeing the same with my locally built app (debug=true) with OTA debugging.

Nexus 7, latest Android updates installed, Tabris 1.3.0

Tabris team, is there a fix for this issue?

**Comment by gosia-eclipsesource** [comment]
No fix for now unfortunately. We will soon be updating to a new V8 which no longer supports Eclipse tooling so we are looking into new ways (such as an interactive JS console that will let you inspect a running application). We'll have a close look at this issue in the upcoming iteration in December.

**Comment by cookieguru** [comment]
I realize this request might fall on deaf ears when talking to an Eclipse shop, but can you investigate other protocols such as the [Mozilla Remote Debugging Protocol](https://wiki.mozilla.org/Remote_Debugging_Protocol) or the [Chromium Remote Debugging Protocol](https://developer.chrome.com/devtools/docs/debugger-protocol)?  I'm partial to one of those since I can plug it right in to one of the JetBrains IDEs.

**Comment by mpost** [comment]
@cookieguru These protocols would make a good fit and we are investigating those and other solutions to improve the debugging support.

**Comment by peterzen** [comment]
@cookieguru +1

**Comment by mpost** [comment]
I am closing this issue in favor of the new debugging support as outlined by @cookieguru.
