### ISSUE TITLE
parent.children().last() cannot be used as a layout reference for the first child

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#595]
The last widget is `undefined` if the parent has no children, which now cannot be set as a layoutData reference. The following error gets thrown: `Ignored unsupported value for property "layoutData": Invalid value for '...': first element must be a percentage or a widget reference`.

Using `"prev()"` as a reference instead works as expected.

Example:

```javascript
var page = tabris.create("Page", {topLevel: true}).open();
console.log(page.children().last());
tabris.create("Composite", {layoutData: {left: 0, top: [page.children().last(), 0]}}).appendTo(page);
```

**Comment by tbuschto** [comment]
The documentation never states that null or undefined is accepted as the first array parameter. It's also not a good idea to allow that since an edge can also be a widget, percentage or offset without array, in which case "null" or "undefined" mean "unset"/"reset". 

This is a small braking change on the behavior of layoutData outside of the properties contract.
