### ISSUE TITLE
device.uuid 

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#609]
cordova supports device.uuid to get the phone/tablet uuid, this seems to be missing on tabris's device object

**Comment by mpost** [comment]
A UUID as known on iOS does not exist on Android. It can in fact even be harmful to rely on the UUID (even on iOS) since the device might change its owner so the UUID would not point to the correct user.

It would be better practice to create a user id locally for the "current user" or to use another authentication mechanism.

**Comment by bFlood** [comment]
I don't want to use the UUID for user auth (for the reasons you mention), I would like to use it to identify the device itself. the vague emulation on Android would be fine

if you store your own unique id for a device, it will get cleared out when the user uninstalls the app.

this isn't a major issue, I just thought it would be nice since it already exists in cordova

**Comment by mpost** [comment]
We have discussed this issue again and came to the conclusion that it does not sufficiently cover all use cases so we are not planning to add support for an UUID.

**Comment by natanraj** [comment]
I am having a need of having a unique identifier of that device. How to do it ? UUID felt comfortable even on android for me in the Cordova based hybrid apps.

**Comment by mpost** [comment]
You should just create a random id and store that in the localStorage. This id will identify the app on the current device.

**Comment by natanraj** [comment]
@mpost , i too thought this as a first approach. But if I have stored this for trace-ability at server & user reinstalls the app, i will get a new ID for this device.  This will defeat the purpose that I am speaking with the same device.    Will Push notification Registration ID be alternative?

**Comment by cookieguru** [comment]
Since iOS 5, Apple has removed the ability for developers to get a unique string that identifies the device ([this article](https://www.tune.com/blog/apple-deprecates-udid-time/) attempts to explain why).  Thus, you can only get a universally unique identifier (UUID) which is regenerated every time the app is installed.  Since you can do the same thing in your JS code (with more control), there is no reason for it to be implemented on the native side.

You could look in to [https://github.com/mgcrea/cordova-secureudid](mgcrea/cordova-secureudid) for iOS and [https://github.com/centrual/cordova-plugin-udid/](centrual/cordova-plugin-udid) for Android though it looks like the former only accesses properties that are normally available with `tabris.device`.

**Comment by natanraj** [comment]
@cookieguru  Thanks..

**Comment by mpost** [comment]
There is also the https://developers.google.com/instance-id/ but that is tied to the cloud messaging service
