### ISSUE TITLE
Add scroll listener to CollectionView

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#651]
Currently it is not possible to be informed when the scrolling position of a CollectionView is changed.

**Comment by ralfstx** [comment]
@mpost Would that be a `scroll` listener that reports the index of the first (and last?) visible item every time a new items is scrolled into view? What do the mobile platforms offer?

**Comment by mpost** [comment]
the index of the position could be provided on ios and android afaik.

**Comment by ralfstx** [comment]
The index of the first item may not be that helpful to find out if you're close to the end when you don't know how many items fit on the screen, is it? For example, the following code would not work when there are more than 20 items on the screen:

```js
collectionView.on("scroll", function(view, index) {
  if (index > items.length - 20) {
    loadNewItems();
  }
});
```

**Comment by mpost** [comment]
On Android the `RecyclerView` the tow layout managers `LinearLayoutManager` (currently in use by Tabris.js) and the `GridLayoutManager` offer the following methods that can be triggered during scrolling. So on Android we can fire events in that realm either continuously or more efficiently when one of the values changes.

```java
int findFirstVisibleItemPosition();
int findFirstCompletelyVisibleItemPosition();
int findLastVisibleItemPosition();
int findLastCompletelyVisibleItemPosition();
```

**Comment by ralfstx** [comment]
@patrykmol @tbuschto Would we get the same events on iOS and Windows as well?

**Comment by patrykmol** [comment]
@ralfstx These are the events available in iOS. I can also get all of the visible cells in each of these events and pass them / get information about the so it would be possible to get behaviour similar to Android.

```
- scrollViewDidScroll:
- scrollViewWillBeginDragging:
- scrollViewWillEndDragging:withVelocity:targetContentOffset:
- scrollViewDidEndDragging:willDecelerate:
- scrollViewShouldScrollToTop:
- scrollViewDidScrollToTop:
- scrollViewWillBeginDecelerating:
- scrollViewDidEndDecelerating:
```

**Comment by ralfstx** [comment]
We agreed on introducing an event named `scroll` similar to the `ScrollView` API. If possible, clients also provide the current scroll offset as an object `{x: number, y: number}`.

In addition, we'll introduce two read-only properties `firstVisibleItem` and `lastVisibleItem` to provide the *index* of the first and last item that is (partially) visible on screen.

In order to load more items when a certain scroll position is reached, a scroll listener would have to check one of these properties on every scroll event. We'll have to evaluate the effect on scrolling performance and look for alternatives if this approach turns out to cause a noticeable slowdown.

**Comment by ralfstx** [comment]
Small adjustment: let's call the properties `firstVisibleIndex` and `lastVisibleIndex` instead of <code>...<del>Item</del></code>. In JS, the item index is needed rather than the item reference.

**Comment by mpost** [comment]
We agreed on calling the scroll event arguments `{deltaX: number, deltaY: number}`. I have updated ralfs comment accordingly.
