### ISSUE TITLE
Real fullscreen

### ISSUE THREAD

**Issue by sergio-doman** [eclipsesource/tabris-js#665]
Hi,
now we have "tabris.ui.set("toolbarVisible", false);" which hides toolbar but I can still see time and battery indicator. But I'm looking for the way to show some image in real fullscreen mode - w/o any other information.
Thank you

**Comment by mpost** [comment]
Currently we don't support that yet. We are aware of its usefulness and have it on our feature list for an upcoming release.

**Comment by ralfstx** [comment]
Related: #171

**Comment by ralfstx** [comment]
In Android, there are two different fullscreen modes called [*Lean Back* and *Immersive*](http://developer.android.com/design/patterns/fullscreen.html), that differ in the gestures used to exit fullscreen mode.

All systems also seem to support translucent system bars.

I'd prefer an enum property like `displayMode` to a boolean one, because that would allow us to add additional variants in the future. In the first version, valid properties could be `"fullscreen"` and `"normal"`.

The obvious object to hold the new property seems to be `tabris.ui`.

**Comment by ralfstx** [comment]
Implemented on Android and iOS. You can now use `tabris.ui.set("displayMode", "fullscreen");` to hide the system bar.
