### ISSUE TITLE
Incorrect path returned by getResourceLocation()?

### ISSUE THREAD

**Issue by maxapps** [eclipsesource/tabris-js#695]
In addition to the previously mentioned issue with getResourceLocation() not working at all in the developer app, it may not be returning a valid location when creating a debug version of apk for Android.

I am storing a test audio file at **resources/audio/aboard.mp3** and calling **getResourceLocation()** from the file **js/PtgLib.js** as follows:
> path = tabris.app.getResourceLocation('resources/audio/aboard.mp3');
> console.log(path);
> window.plugins.NativeAudio.preloadSimple('aboard', path, ...

The log call results in this text:
> file:///android_asset/www/bundled_tabris_js_launcher/user_app/resources/audio/aboard.mp3

And the error message generated by the NativeAudio call is:
> java.io.FileNot-FoundException: www/file:///android_asset/www/bundled_tabris_js_launcher/user_app/resources/audio/aboard.mp3

When I unzipped the apk file, the mp3 file is stored at:
> assets\www\bundled_tabris_js_launcher\user_app\resources\audio\aboard.mp3

It's interesting that the error message seems to indicate that an extra 'www/' was prepended to the path. I just noticed this and it makes me wonder of the NativeAudio plugin is expecting a partial path. I will try another version which chops off the "file:///android_asset/" portion of the path before passing it to the NativeAudio call.

Please advise if you have any other ideas.

Thanks

**Comment by maxapps** [comment]
It is confirmed.  Removing everything up to and including "www/" from the beginning of the string returned by the call to ***getResourceLocation()** fixed the problem.

The code now looks something like this:
```javascript
var path = tabris.app.getResourceLocation('resources/audio/aboard.mp3');
path = path.substr(path.indexOf('www/') + 4);
window.plugins.NativeAudio.preloadSimple('aboard', path, function(msg) {
    console.log('Audio loaded!');
}, function(msg) {
    console.warn('error: ' + msg);
});
```

This results in **/bundled_tabris_js_launcher/user_app/resources/audio/aboard.mp3** being passed to NativeAudio.preloadSimple().

I'm not certain if this is a problem with Tabris or with the NativeAudio plugin but it should be noted that, even if NativeAudio were not adding "www/" to the beginning of the string, it would not match what is currently being sent.

**Comment by mpost** [comment]
@maxapps Thanks for the info. Apparently the audio plugin performs some path interpolation itself.

The best case scenario would be if the plugin could simply deal with the fully qualified path itself but since that is not the case we could think about adding another version of `getResourceLocation()`.

Maybe `getResourceLocationRelative()` that would return the location of the resource relative to the `www` folder. In your scenarion that would be `bundled_tabris_js_launcher/user_app/resources/audio/aboard.mp3`.

**Comment by mpost** [comment]
@maxapps Since you closed the issue you are happy with your current solution?

**Comment by maxapps** [comment]
Yes, it doesn't seem to be a problem with tabris. You can't be expected to
return different types of data for each and every plugin.

Do I need to do anything special to make certain this information is
available to anyone else who attempts to use the NativeAudio plugin?

**Comment by mpost** [comment]
Currently we are only tracking these information in the github issues with the label "compatibility cordova". We are currently compiling a list of plugins that are know to work. See here for more details: https://tabrisjs.com/documentation/latest/cordova#other-cordova-plugins

**Comment by ralfstx** [comment]
Two observations:

1. The path returned by the log call contains the segment `/android_asset/` whereas the mp3 file apparently resides in `/assets/`. @mpost can't this be fixed?

2. The NativeAudio plug-in might prepend the `www/` segment because the given path is relative, i.e. it does not start with a slash. `getResourceLocation()` returns a URL, so the `file://` prefix has to be removed.

**Comment by mpost** [comment]
@ralfstx regarding 1. the path has to contain the android_asset path as that is the root folder of a file:// resource. As we discussed above, a variation of the getResourceLocation() could provide the path in a relative fashion (relative to the www root folder).
