### ISSUE TITLE
How to make call's (tel:), send sms's (sms:) or show a map (geo:) using buttons?

### ISSUE THREAD

**Issue by celopez1990** [eclipsesource/tabris-js#716]

**Comment by cookieguru** [comment]
Combined with the Cordova [InAppBrowser](https://github.com/apache/cordova-plugin-inappbrowser) plugin, this snippet works:
```js
tabris.create('Page', {
	title: 'Phone button',
	topLevel: true
}).append(
	tabris.create('Button', {
		text: 'Call'
	}).on('select', function() {
		cordova.InAppBrowser.open('tel:18004444444', '_system');
	})
).open();
```
You will need to [build](https://tabrisjs.com/documentation/latest/build) an app since that plugin is not included with the default development app.  In `cordova/config.xml` add:
```xml
<plugin name="cordova-plugin-inappbrowser" version="1.1.1" />
```
And the plugin will be bundled with your debug and release builds.  With debug builds you can continue to load a script from a URL.

**Comment by celopez1990** [comment]
thank you very much....
