### ISSUE TITLE
Switch widget does not support baseline alignment

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#750]
I would expect to be able to baseline align a `Switch` with a `TextView` in a way that the text is vertically centered with the text. The following snippet demonstrates the misalignment while the text is properly aligned on Android

``` js
var page = tabris.create("Page", {
  title: "Switch",
  topLevel: true
}).open();

tabris.create("Switch", {
  left: 16, top: 16,
}).appendTo(page);

tabris.create("TextView", {
  left: "prev() 12", baseline: "prev()",
  text: "Switch"
}).appendTo(page);

page.open();
```

**Comment by patrykmol** [comment]
It is unclear why baseline does not work with Switch. During constraint creation Switch's size is (0;0) which might be the issue (Switch has hardcoded size by Apple).

**Comment by karolszafranski** [comment]
The issue is old, and many things changed since it was created. However, I think it's working correctly.

Snippet:
```js
new tabris.Switch({left: 16, top: 16}).appendTo(tabris.ui.contentView);
new tabris.TextView({left: 'prev() 16', baseline: 'prev()', text: 'aaa'}).appendTo(tabris.ui.contentView);
```

Screenshoots:

| Original  | Zoomed  |
| ------------- |-------------|
|  ![simulator screen shot - iphone se - 2017-09-18 at 15 50 54](https://user-images.githubusercontent.com/1746396/30545333-928dc178-9c89-11e7-9678-cf4bbce95371.png)  | <img width="1392" alt="screen shot 2017-09-18 at 15 51 42" src="https://user-images.githubusercontent.com/1746396/30545332-928a1b22-9c89-11e7-8fbe-9f8e684670ca.png"> |

Please reopen if I'm wrong
