### ISSUE TITLE
Support zooming and panning ImageView's image

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#775]
Currently the image appears at a fixed position according to the "scaleMode" property. It would be useful to additionally let the user interactively pan and zoom the image showed in the ImageView.

**Comment by bFlood** [comment]
+1

**Comment by cookieguru** [comment]
Or if possible perhaps add zooming ability to `Composite`, so we could zoom in on `Canvas` as well?

**Comment by tbuschto** [comment]
I think ScrollView would be a nice fit if it can be supported on all platforms.

**Comment by ralfstx** [comment]
Using a ScrollView would require setting the zoomed image as content, which would keep the full-size image in memory, wouldn't it? An ImageView may handle this more efficiently and only map the visible area into memory.

**Comment by mpost** [comment]
I agree with @ralfstx statement. If you want to efficiently display an image in a zoomed fashion you will want to use subsampling and tiling for it. Since these features would need to provided by the ImageView a generic pinch to zoom on Composite or via ScrollView would not be sufficient.

**Comment by maxapps** [comment]
Any progress on this issue?

**Comment by mpost** [comment]
No immediate progress. For single images a WebView could be used to display the image.

**Comment by cpetrov** [comment]
@maxapps For reference, see the map implementation in the Tabris Con app:

https://github.com/eclipsesource/tabris-con/blob/master/html/map.html
https://github.com/eclipsesource/tabris-con/blob/master/src/pages/Map.tsx

**Comment by maxapps** [comment]
@cpetrov Thanks for the tip.  I created a working version using WebView but it didn't meet my requirements due to the way the WebView controlled display and resizing of the image.

I ended up creating  my own by placing a full-size image on a page then using a combination of  **touchStart** and **pan** events to manually change the **centerX** and **centerY** properties of the image. It's not perfect but will do for now. Interestingly enough, I also"discovered" that you cannot use negative values on **left** and **top** to move an image but using negatives works fine with **centerX** and **centerY**.

BTW - Why are we limited to choosing between vertical or horizontal scrolling? Don't the native platforms provide a way to scroll both directions?

**Comment by mpost** [comment]
The layout we use on Android does not support negative margins. https://issuetracker.google.com/issues/37136609

**Comment by mpost** [comment]
Closing as implemented.
