### ISSUE TITLE
iOS: highlightOnTouch prevents collectionView "selected" event

### ISSUE THREAD

**Issue by shaialon** [eclipsesource/tabris-js#796]
In the rss example, see branch : ["highlight-bug"](https://github.com/eclipsesource/tabris-js-rss-example/tree/highlight-bug)

It works nicely on Android, but on iOS the collectionView selections seem not to fall through. 
In file [news_widget.js, line 73](https://github.com/eclipsesource/tabris-js-rss-example/blob/highlight-bug/src/components/news_widget.js#L73), removing `highlightOnTouch:true` will make the app functional but without the highlights.

**Comment by patrykmol** [comment]
I finally have gotten to the bottom of the problem. This is a problem because for highlighting cell we use a gesture recognizer that is provided by a `Composite` widget instead of using collection view delegate callbacks. Solution would be to reimplement this with those callbacks if `Composite` is used as a cell.

**Comment by patrykmol** [comment]
Non reproducible as of latest nightly/2.0.
