### ISSUE TITLE
Referencing a widget in layoutData that is not a sibling crashes the windows client

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#822]
Consider this:

```
var page1 = new tabris.Page();
var page2 = new tabris.Page();
var widget1 = new tabris.Button({id: "w1"});
var widget2 = new tabris.Button({id: "w2", top: "#w2 10"});
widget1.appendTo(page1);
widget2.appendTo(page2);
```

This renders top of widget2 as would be expected, which confused the windows client so much that it crashes completely. My preferred solution for this issues would be to render top as if w2 didn't exist at all.

**Comment by tbuschto** [comment]
Can also happen on re-parenting obviously

**Comment by ralfstx** [comment]
We should not *reject* widget references in `set`, because even if the widget is not yet a sibling, it may become one later.

What we can and should do is to *skip* references to widgets that aren't (yet) siblings, just as we filter references to widgets that don't (yet) exist before sending them over the native bridge.
