### ISSUE TITLE
Trouble getting Tabris working with Firebase

### ISSUE THREAD

**Issue by daniel-graham** [eclipsesource/tabris-js#823]
I've been playing around with the template-app starter project to use for an assignment and it seems that I can't use Firebase in my Tabris app. I keep getting a Reference error for process.

I've tested firebase with a standard node application and it works fine which leads me to believe I maybe missing something or misunderstanding how Tabris works or its bootstrapping process. I'm a new dev so sorry if this is a stupid question or isn't really an issue... I'll also try posting this to StackOverflow if needed...

![image](https://cloud.githubusercontent.com/assets/10553856/14502612/21160ace-017a-11e6-9412-6d493794303b.png)

![image](https://cloud.githubusercontent.com/assets/10553856/14502625/31275468-017a-11e6-8f74-55d108d43bfb.png)

![image](https://cloud.githubusercontent.com/assets/10553856/14502982/ef409aa8-017b-11e6-94f8-cd9076c02e73.png)

**Comment by cookieguru** [comment]
This is because `firebase` depends on the Node module `process` which is not implemented in [tabris-js-node](https://github.com/eclipsesource/tabris-js-node).  You could try importing the library manually but `process` likely depends on many other libraries and it's probably not worth chasing all those.

The recommended approach would be the same as mentioned in #763 with the only difference being that this time [it might actually be possible](https://github.com/firebase/firebase-login-demo-phonegap).

**Comment by bFlood** [comment]
there was also this comment by tabris about forthcoming websocket support (and specifically, firebase support)
https://github.com/eclipsesource/tabris-js/issues/188#issuecomment-196724300

**Comment by cookieguru** [comment]
I mis-spoke, `process` **is** impimented in `tabris-js-node` but you need to explicitly add it to your `package.json`:
```js
    "tabris-js-node": "^0.1.0"
```

**Comment by mpost** [comment]
process is a only a stub implementation in `tabris-js-node` so it will not work with the firebase npm module. That being said the firebase integration is possible with the upcoming WebSocket support with the web based websocket integration. You will have to set a property though: `Firebase.INTERNAL.forceWebSockets();`. Please stay tuned for that.

**Comment by maxapps** [comment]
Any update on when this is expected?

**Comment by mpost** [comment]
No immediate update yet. We are still working on the websocket integration.

**Comment by mpost** [comment]
The WebSocket support has been added in Tabris.js 1.10.

**Comment by mpost** [comment]
Please use the tabris-firebase-plugin at https://github.com/eclipsesource/tabris-plugin-firebase. Contributions are welcome.

**Comment by maxapps** [comment]
I don't understand why this issue has been closed. As far as I can tell, Tabris 2.2 **still** doesn't work with firebase and the tabris-firebase-plugin is not a viable solution because it only supports a very small subset (cloud messaging and analytics) of firebase features. What about Firebase Realtime Database, Firebase Storage, and Firebase Authentication?

Adding websocket support hasn't seemed to fix the issue. Simply adding the [official firebase package](https://www.npmjs.com/package/firebase) to the default tabris project fails on the line where the package is required.

Here are the steps I took:

1. Created a new project using `tabris init`.
2. Tested on phone to ensure it works. Everything is good.
3. Added the firebase module using `npm install --save firebase`.
4. Added a single line to the project `let firebase = require('firebase');`.
5. Tested on the phone and got the following error.

> Could not load main module: Error: Cannot find module 'util'
>    at e.findModule (<anonymous>:1:555)
>    at e.value (<anonynous>:1:2521)
>    at ./node_modules/faye-websocket/lib/faye/websocket.js:7:14
>    at e.get (<anonymous>:1:2311)
>    at e.value (<anonymous>:1:2533)
>    at ./node_modules@firebase/database/dist/cjs/src/nodePatches.js:20:24
>    at e.get (<anonymous>:1:2311)
>    at e.value (<anonymous>:1:2569)
>    at ./node_modules/@firebase/database/dist/cjs/index.node.js:31:1
>    at e.get (<anonymous>:1:2311)

Has anyone managed to get the [Firebase JS SDK](https://firebase.google.com/docs/reference/js/) working with Tabris.js?

Sorry to take such a negative tone but issues like this are part of what keeps Tabris.js from rising to the next level and gaining some real traction. You guys have done great work getting it to something which is pretty good but it has the potential to be something really great.

**Comment by cookieguru** [comment]
The official Firebase package is designed to work with Node.  Tabris.js is not using Node to execute the JS; rather it uses [J2V8](https://github.com/eclipsesource/J2V8/) on Android, the native JSCore on iOS, and the native Chakra on Windows.  This means some of Node's built-in libraries are not available.  The good news is that there is a shim available and will let you work around the missing `util` module.  Simply `npm install --save tabris-js-node` and try again.  [`tabris-js-node`](https://github.com/eclipsesource/tabris-js-node) provides some of the core modules, but not all.  Some would require functionality that is not possible only in JS and would require some code on the native side.

**Comment by mpost** [comment]
In general, what firebase features are you most interested in seeing supported? We should expand the support of the `tabris-plugin-firebase`.

**Comment by maxapps** [comment]
@cookieguru  Thanks for information about tabris-js-node -- I will give it a try. The official package is designed for use with Node **and** the browser. I understand the difference but the target audience for Tabris is JS developers and that means a lot of people accustomed to programming in a browser environment. The real issue is that the only documentation for using Firebase with Tabris.js is here, on the GitHub page and the issue has been closed when there was no working solution. I know part of that is because of the small user base but there won't be a large user base until things like this are worked out.

@mpost  Ultimately, that would be the best solution. At a minimum, Authentication and the Realtime Database should be supported. Firebase Storage would also be a big plus. I have a pet project which uses these on a web site "hosted" on Firebase Hosting and have been planning to build an App which ties into the same system. I finally have some time on my hands but discovered that Tabris doesn't really work with the Firebase JS SDK (at least not until the @cookieguru  comment above). I also started work on a Tabris-specific library last night which uses the Firebase REST API. It works pretty well but only supports email authentication and database get() and set() functions at the moment. Even if the method mentioned by @cookieguru works, I might continue with the REST library since it will probably be a lot smaller and have fewer dependencies.

**Comment by maxapps** [comment]
@cookieguru 
Including the node compatibility module didn't work.
It was installed using `npm install --save tabris-js-node` and included before Firebase as
`require('tabris-js-node');`
`const firebase = require('firebase');`

Now the error message says it can't find the 'stream' module.

**Comment by cookieguru** [comment]
@maxapps Sorry I didn't mean to send you down a rabbit hole.  I wasn't sure if there how many more compatibility issues there were with that plugin.  But after all, if it worked, why would we need [tabris-plugin-firebase](https://github.com/eclipsesource/tabris-plugin-firebase)?

**Comment by maxapps** [comment]
@cookieguru No problem, it was definitely worth trying. I think the REST version is actually going to work.

**Comment by mpost** [comment]
@maxapps How would you see the support for the new Firebase cloud firestore vs the older realtime database. I think moving foeward the firestore is the more interesting technology, which could support in the `tabris-plugin-firebase`.

**Comment by maxapps** [comment]
@mpost  In my opinion, both are needed but I would support Realtime Database first. Firestore is definitely more interesting and could possibly replace the current database.  But that isn't going to happen for several years since there are a couple hundred thousand existing apps which use the Realtime Database. Firestore isn't even out of beta yet and this quote from [The Firebase Blog](https://firebase.googleblog.com/2017/10/introducing-cloud-firestore.html) states, they plan to keep both products around.

> So, if you're a Firebase Realtime Database user today, we think you'll love Cloud Firestore. However, this does not mean that Cloud Firestore is a drop-in replacement for the Firebase Realtime Database. For some use cases, it may make sense to use the Realtime Database to optimize for cost and latency, and it's also easy to use both databases together. You can read a more in-depth comparison between the two databases here.
> 
> We're continuing development on both databases and they'll both be available in our console and documentation.

**Comment by mpost** [comment]
@maxapps I tend to agree. We have experimented with the firestore and found its data modeling capabilities superior to the realtime database. Some of its querying capabilities are a bit lacking but in general it should be the way forward if a new project is started.
