### ISSUE TITLE
Android Marshmallow - Camera fails

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#836]
you can't use the camera on Android6 unless the user explicitly sets permission for the app in the application manager. It looks like something is going wrong with the new permissions framework and the camera. You can see the issue in the tabris.js playstore app, cordova-camera demo (slide the debug log out to see the error)

looks like it may be an issue with cordova6.0 and may need an upgrade to 6.1
http://stackoverflow.com/questions/36450559/cordova-camera-plugin-permission-denial-in-android-6-0

**Comment by mpost** [comment]
Plugins which have not yet updated will not get the permission they require... a similar thing applies to the zxing barcode scanner plugin for example.

You could request the permission yourself with the help of this plugin for example: https://github.com/dpa99c/cordova-diagnostic-plugin

**Comment by bFlood** [comment]
but I thought the official cordova camera plugin was already updated?

I will give the diagnostics plugin a try and let you know, thanks

**Comment by mpost** [comment]
Let us know if it works for you.

**Comment by bFlood** [comment]
with that plugin installed, I get this when the app first loads (debug and release). no tabs appear and the app eventually crashes

``` log
Could not create object "rwt.widgets.TabItem" (reason: Failed resolution of: Landroid/support/v7/widget/TintManager;)
Could not set properties (reason: Invalid index 2, size is 0)
```

**Comment by mpost** [comment]
That does not sound very encouraging... We would have to look into that.

**Comment by bFlood** [comment]
that would be great, thanks. while there is a work around, having the user manually change permissions for the app is not optimal

**Comment by bFlood** [comment]
I would say this is a bug, the camera is a standard plugin and is not working on new Android devices

**Comment by mpost** [comment]
Since the plugin `https://github.com/apache/cordova-plugin-camera` is also used in the example app it is able to run fine even on Android 6. In the example app there is no need for the camera permission since the plugin actually defers the image taking process to the camera app on the device.

Could you narrow down your problem a bit more?

**Comment by mpost** [comment]
Maybe this is related? http://stackoverflow.com/a/36567506/271877

**Comment by bFlood** [comment]
@mpost - the camera on the example app does not work on my Android6 device, its the same error

**Comment by mpost** [comment]
I am running the example on a Samsung Galaxy S6 and a Nexus 6p. Both on Android 6. The apps do not declare the camera permission and therefore are not eligible to request the permission at runtime:

![image](https://cloud.githubusercontent.com/assets/73655/15213853/0afd5aee-184a-11e6-956d-63e373e344ea.png)

**Comment by bFlood** [comment]
sorry, I was out of the office for a little bit

here an android 6 testing device running the tabris example app:

![screenshot_20160512-100448](https://cloud.githubusercontent.com/assets/404991/15217429/8c026150-1829-11e6-989f-fa4cfece6a8a.png)
![screenshot_20160512-100409](https://cloud.githubusercontent.com/assets/404991/15217449/9aa035ac-1829-11e6-8b4c-4912dbc4b4da.png)
![screenshot_20160512-100401](https://cloud.githubusercontent.com/assets/404991/15217456/9eec3cbe-1829-11e6-8b29-3ede7b44d681.png)
![screenshot_20160512-100645](https://cloud.githubusercontent.com/assets/404991/15217459/a2140c5a-1829-11e6-807d-9196d74edb25.png)

**Comment by mpost** [comment]
I just created a new app (with Tabris 1.8 nightly) and added the cordova camera plugin. Than i used [takePicture](https://github.com/apache/cordova-plugin-camera#cameragetpicturesuccesscallback-errorcallback-options) to take a snapshot. This prompted me to allow access the local storage and used the devices camera app to take a picture. So in the end the storage permission needed to be granted but no explicit camera permission since the plugin uses the devices camera apps.

Therefore i would assume that your app uses other plugins that would require the camera permission. Maybe for barcode scanning? We removed that plugin from the tabris-js-app as it interfered with the build process. https://github.com/eclipsesource/tabris-js-app/blob/master/Gruntfile.js#L31

**Comment by bFlood** [comment]
ok, I think you are correct. Its the barcode scanner plugin causing the issue, not the camera. I was confused when the tabris.js example app had the same issue but once you recompiled it with the latest camera plugin, it worked correctly right?

thanks

**Comment by mpost** [comment]
Correct. The camera plugin works as expected.

**Comment by mpost** [comment]
Closing this since the barcode plugin has to be updated.
