### ISSUE TITLE
Action with no text

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#862]
When you create an action that just has an image and no text, you get a flash of [No Text] before the image renders.

**Comment by ralfstx** [comment]
On which platform?

**Comment by cookieguru** [comment]
If Android; possibly related to @mpost's fix of #721

**Comment by dested** [comment]
Platform is android. Yes it is the same issue, I just had the verbiage wrong. I tested this with tabris 1.7 and it is still happening for me. I will try to put together an example tonight.

**Comment by mpost** [comment]
The described behavior is correct. We show this place holder text upfront.

**Comment by mpost** [comment]
https://github.com/eclipsesource/tabris-js/issues/721 is in fact not the attempt to remove this place holder text but to make sure that user provided text is always shown.

When loading the image locally you would not see the text when the images are loaded very quick.

On a side note... you should _ALWAYS_ provide a text for your actions since you can long press on an action showing you a tooltip of the meaning.

**Comment by mpost** [comment]
We have removed the placeholder text for Tabris.js 2.0. Closing this for now.
