### ISSUE TITLE
"tap" not triggered on disabled images

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#900]
It is expected ~~not~~ to be able to interact with an ImageView using gestures if the ImageView is disabled.

``` javascript
var page = new tabris.Page({
  title: "Using an image view as a button",
  topLevel: true
});

var image = new tabris.ImageView({
  layoutData: {centerX: 0, centerY: 0, width: 400, height: 400},
  image: {src: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Llama_lying_down.jpg/2560px-Llama_lying_down.jpg"},
  highlightOnTouch: true,
  enabled: false
}).on("tap", function() {
  console.log("Image tapped.");
}).appendTo(page);

page.open();
```

**Comment by mpost** [comment]
I would not expect the tap to be disabled when the widget is disabled. Rather a "select" on a button should not fire but the tab gesture (or any other gesture) could also be valuable when the widget is disabled.

**Comment by mpost** [comment]
Research revealed that it is not possible to receive a touch event when it the widget is disabled. The event is not dispatched to the widget.

Since gestures and `touch*` events are both created from the same touch listener there is no difference between the two.

In order to ensure Tabris.js consistency i would recommend to not dispatch touch events on iOS as well.

**Comment by tbuschto** [comment]
Agreed. @ralfstx Should we make this an iOS only issue?

**Comment by ralfstx** [comment]
Yes. @cpetrov I took the freedom to comment out your "Edit" in the original post as it stated the opposite of the current findings.
