### ISSUE TITLE
using tabris without Cordova

### ISSUE THREAD

**Issue by oxitech239** [eclipsesource/tabris-js#961]
This is an informative question.

Is it possible to integrate TabrisJS with another framework separate from Cordova/Express and even NodeJS ? Is it worth considering or would the effort kill of it's potential benefits ?

**Comment by cookieguru** [comment]
Depends on what your goal is.  The Tabris.js JavaScript libraries pair well
with the native binaries (which are not* open source).  The JS library is
very domain specific.  It's not designed to be a general purpose library
(like underscore).  That said, it certainly _could_ be used separately
within Node.js and is very easy to do so since it is listed in npm.

*Native client sources are available with the Organization plan

**Comment by oxitech239** [comment]
Not being an experienced dev myself. With domain specific you mean it is tied to NodeJS and cannot be made to work with another stack such as Luvit which is based on Lua ?

**Comment by cookieguru** [comment]
By domain I mean a specific area of knowledge.  That is, the Tabris.js JavaScript libary is tightly coupled to the Tabris.js native binaries--if you were to connect either of those to something else you would have to reimplement the protocols exactly the same way.  For example, you could write a client in C so that the same code that powers a mobile app could also power a desktop app with the same codebase.

For sure you could do the same thing in Lua as Tabris.js does with JavaScript.  You'd probably be starting with something like [AndroLua](https://github.com/mkottman/AndroLua) which is similar to what Tabris.js uses.  Tabris.js uses [J2V8](https://github.com/eclipsesource/J2V8) to run JavaScript on Android.

**Comment by oxitech239** [comment]
Thanks, i've found the https://github.com/nondev/jua repository which offers LuaJIT for a number of platforms (Windows, Mac OS X, Linux, Android and iOS) I hope to eventually gather some people to work on the idea of getting such a project going.

**Comment by mpost** [comment]
Closing this issue for now. @oxitech239 feel free to reopen if required
